[package]
name = "sc-authority-discovery"
version = "0.44.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate authority discovery. (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { workspace = true }

[dependencies]
codec = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
ip_network = { workspace = true }
libp2p = { features = ["ed25519", "kad"], workspace = true }
multihash = { workspace = true }
linked_hash_set = { workspace = true }
log = { workspace = true, default-features = true }
prost = { workspace = true }
rand = { workspace = true, default-features = true }
thiserror = { workspace = true }
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sc-network-types.workspace = true
sc-network-types.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-authority-discovery.workspace = true
sp-authority-discovery.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
async-trait = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
sp-tracing = { default-features = true, path = "../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }

[features]
std = [
	"log/std",
	"multihash/std",
	"codec/std",
	"sc-client-api/std",
	"sc-network/std",
	"sc-network-types/std",
	"sp-blockchain/std",
	"prometheus-endpoint/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-network/try-runtime",
	"sp-api/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
