[package]
name = "pallet-authority-discovery"
version = "37.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME pallet for authority discovery (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-session = { features = ["historical"], workspace = true }
sp-application-crypto.workspace = true
sp-authority-discovery.workspace = true
sp-runtime.workspace = true

[dev-dependencies]
sp-core = { default-features = true, path = "../../primitives/core" }
sp-io = { default-features = true, path = "../../primitives/io" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"scale-info/std",
	"sp-application-crypto/std",
	"sp-authority-discovery/std",
	"sp-runtime/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-session/try-runtime",
	"sp-runtime/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-io/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime"
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-session/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
