[package]
name = "sp-consensus"
version = "0.40.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Common utilities for building and using consensus engines in substrate. (polkadot v1.15.0)"
documentation = "https://docs.rs/sp-consensus/"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true }
futures = { features = ["thread-pool"], workspace = true }
log = { workspace = true, default-features = true }
thiserror = { workspace = true }
sp-core.workspace = true
sp-core.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true

[dev-dependencies]
futures = { workspace = true }
sp-test-primitives = { path = "../../test-primitives" }

[features]
default = []
std = [
	"log/std"
]
runtime-benchmarks = [
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-test-primitives/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"sp-test-primitives/try-runtime",
	"sp-core/try-runtime"
]
