[package]
name = "asset-test-utils"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
description = "Test utils for Asset Hub runtimes. (polkadot v1.15.0)"
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive", "max-encoded-len"], workspace = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-assets.workspace = true
pallet-balances.workspace = true
pallet-timestamp.workspace = true
pallet-session.workspace = true
sp-io.workspace = true
sp-runtime.workspace = true
cumulus-pallet-parachain-system.workspace = true
cumulus-pallet-xcmp-queue.workspace = true
pallet-collator-selection.workspace = true
parachains-common.workspace = true
cumulus-primitives-core.workspace = true
parachain-info.workspace = true
parachains-runtimes-test-utils.workspace = true
xcm.workspace = true
xcm-builder.workspace = true
xcm-executor.workspace = true
pallet-xcm.workspace = true
pallet-xcm-bridge-hub-router.workspace = true

[dev-dependencies]
hex-literal = { workspace = true, default-features = true }

[build-dependencies]
substrate-wasm-builder.workspace = true
substrate-wasm-builder.default-features = true

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-collator-selection/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"pallet-xcm-bridge-hub-router/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"parachains-common/std",
	"parachains-runtimes-test-utils/std",
	"sp-io/std",
	"sp-runtime/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	"substrate-wasm-builder/std"
]
runtime-benchmarks = [
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collator-selection/runtime-benchmarks",
	"pallet-session/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"pallet-xcm-bridge-hub-router/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"parachains-runtimes-test-utils/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"parachain-info/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"substrate-wasm-builder/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-collator-selection/try-runtime",
	"pallet-session/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-xcm/try-runtime",
	"pallet-xcm-bridge-hub-router/try-runtime",
	"parachains-common/try-runtime",
	"parachains-runtimes-test-utils/try-runtime",
	"sp-runtime/try-runtime",
	"parachain-info/try-runtime",
	"xcm-builder/try-runtime",
	"xcm-executor/try-runtime",
	"sp-io/try-runtime",
	"substrate-wasm-builder/try-runtime",
	"xcm/try-runtime"
]
