[package]
name = "pallet-examples"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "The single package with examples of various types of FRAME pallets (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
pallet-default-config-example.workspace = true
pallet-dev-mode.workspace = true
pallet-example-basic.workspace = true
pallet-example-frame-crate.workspace = true
pallet-example-kitchensink.workspace = true
pallet-example-offchain-worker.workspace = true
pallet-example-split.workspace = true
pallet-example-single-block-migrations.workspace = true
pallet-example-tasks.workspace = true

[features]
default = ["std"]
std = [
	"pallet-default-config-example/std",
	"pallet-dev-mode/std",
	"pallet-example-basic/std",
	"pallet-example-frame-crate/std",
	"pallet-example-kitchensink/std",
	"pallet-example-offchain-worker/std",
	"pallet-example-single-block-migrations/std",
	"pallet-example-split/std",
	"pallet-example-tasks/std",
]
try-runtime = [
	"pallet-default-config-example/try-runtime",
	"pallet-dev-mode/try-runtime",
	"pallet-example-basic/try-runtime",
	"pallet-example-kitchensink/try-runtime",
	"pallet-example-offchain-worker/try-runtime",
	"pallet-example-single-block-migrations/try-runtime",
	"pallet-example-split/try-runtime",
	"pallet-example-tasks/try-runtime",
	"pallet-example-frame-crate/try-runtime"
]
runtime-benchmarks = [
	"pallet-default-config-example/runtime-benchmarks",
	"pallet-dev-mode/runtime-benchmarks",
	"pallet-example-basic/runtime-benchmarks",
	"pallet-example-frame-crate/runtime-benchmarks",
	"pallet-example-kitchensink/runtime-benchmarks",
	"pallet-example-offchain-worker/runtime-benchmarks",
	"pallet-example-single-block-migrations/runtime-benchmarks",
	"pallet-example-split/runtime-benchmarks",
	"pallet-example-tasks/runtime-benchmarks"
]
