[package]
name = "sc-consensus-manual-seal"
version = "0.45.0"
authors.workspace = true
description = "Manual sealing engine for Substrate (polkadot v1.15.0)"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { features = ["client-core", "macros", "server-core"], workspace = true }
assert_matches = { workspace = true }
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
thiserror = { workspace = true }
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus.workspace = true
sc-consensus.default-features = true
sc-consensus-aura.workspace = true
sc-consensus-aura.default-features = true
sc-consensus-babe.workspace = true
sc-consensus-babe.default-features = true
sc-consensus-epochs.workspace = true
sc-consensus-epochs.default-features = true
sc-transaction-pool.workspace = true
sc-transaction-pool.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-consensus-aura.workspace = true
sp-consensus-aura.default-features = true
sp-consensus-babe.workspace = true
sp-consensus-babe.default-features = true
sp-consensus-slots.workspace = true
sp-consensus-slots.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-timestamp.workspace = true
sp-timestamp.default-features = true

[dev-dependencies]
tokio = { features = ["macros", "rt-multi-thread"], workspace = true, default-features = true }
sc-basic-authorship = { default-features = true, path = "../../basic-authorship" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
substrate-test-runtime-transaction-pool = { path = "../../../test-utils/runtime/transaction-pool" }

[features]
std = [
	"log/std",
	"sc-basic-authorship/std",
	"sc-client-api/std",
	"sc-consensus/std",
	"sc-consensus-aura/std",
	"sc-consensus-babe/std",
	"sc-consensus-epochs/std",
	"sc-transaction-pool/std",
	"sc-transaction-pool-api/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"prometheus-endpoint/std",
	"substrate-test-runtime-client/std",
	"substrate-test-runtime-transaction-pool/std"
]
runtime-benchmarks = [
	"sc-basic-authorship/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-consensus-aura/runtime-benchmarks",
	"sc-consensus-babe/runtime-benchmarks",
	"sc-consensus-epochs/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-consensus-aura/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"substrate-test-runtime-transaction-pool/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"sc-basic-authorship/try-runtime",
	"sc-client-api/try-runtime",
	"sc-consensus/try-runtime",
	"sc-consensus-aura/try-runtime",
	"sc-consensus-babe/try-runtime",
	"sc-consensus-epochs/try-runtime",
	"sc-transaction-pool/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-consensus-aura/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-timestamp/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"substrate-test-runtime-transaction-pool/try-runtime",
	"sp-consensus-slots/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
