[package]
name = "pallet-contracts-mock-network"
version = "13.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
description = "A mock network for testing pallet-contracts (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive", "max-encoded-len"], workspace = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-assets.workspace = true
pallet-assets.default-features = true
pallet-balances.workspace = true
pallet-balances.default-features = true
pallet-contracts.workspace = true
pallet-contracts.default-features = true
pallet-contracts-uapi.workspace = true
pallet-contracts-proc-macro.workspace = true
pallet-contracts-proc-macro.default-features = true
pallet-insecure-randomness-collective-flip.workspace = true
pallet-insecure-randomness-collective-flip.default-features = true
pallet-message-queue.workspace = true
pallet-message-queue.default-features = true
pallet-proxy.workspace = true
pallet-proxy.default-features = true
pallet-timestamp.workspace = true
pallet-timestamp.default-features = true
pallet-utility.workspace = true
pallet-utility.default-features = true
pallet-xcm.workspace = true
polkadot-parachain-primitives.workspace = true
polkadot-parachain-primitives.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-runtime-parachains.workspace = true
polkadot-runtime-parachains.default-features = true
scale-info = { features = ["derive"], workspace = true }
sp-api.workspace = true
sp-core.workspace = true
sp-io.workspace = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-runtime.workspace = true
sp-tracing.workspace = true
sp-tracing.default-features = true
xcm.workspace = true
xcm-builder.workspace = true
xcm-builder.default-features = true
xcm-executor.workspace = true
xcm-simulator.workspace = true
xcm-simulator.default-features = true

[dev-dependencies]
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }
pallet-contracts-fixtures = { path = "../fixtures" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-contracts/std",
	"pallet-insecure-randomness-collective-flip/std",
	"pallet-proxy/std",
	"pallet-timestamp/std",
	"pallet-utility/std",
	"pallet-xcm/std",
	"scale-info/std",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore/std",
	"sp-runtime/std",
	"xcm-executor/std",
	"xcm/std",
	"pallet-contracts-fixtures/std",
	"pallet-contracts-uapi/std",
	"xcm-simulator/std"
]

runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-contracts/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"pallet-contracts-fixtures/runtime-benchmarks",
	"pallet-insecure-randomness-collective-flip/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"xcm-simulator/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-contracts/try-runtime",
	"pallet-contracts-fixtures/try-runtime",
	"pallet-insecure-randomness-collective-flip/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-xcm/try-runtime",
	"polkadot-parachain-primitives/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-runtime-parachains/try-runtime",
	"sp-api/try-runtime",
	"sp-runtime/try-runtime",
	"xcm-builder/try-runtime",
	"xcm-executor/try-runtime",
	"xcm-simulator/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime",
	"sp-keystore/try-runtime"
]
