[package]
name = "sp-transaction-storage-proof"
version = "34.0.0"
authors.workspace = true
description = "Transaction storage proof primitives (polkadot v1.15.0)"
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { optional = true, workspace = true }
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
sp-core = { optional = true, workspace = true }
sp-inherents.workspace = true
sp-runtime.workspace = true
sp-trie = { optional = true, workspace = true }

[features]
default = ["std"]
std = [
	"async-trait",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-trie/std",
]
runtime-benchmarks = [
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-trie?/runtime-benchmarks",
	"sp-core?/runtime-benchmarks"
]
try-runtime = [
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-trie?/try-runtime",
	"sp-core?/try-runtime"
]
