[package]
name = "parachains-runtimes-test-utils"
version = "16.0.0"
authors.workspace = true
edition.workspace = true
description = "Utils for Runtimes testing (polkadot v1.15.0)"
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive", "max-encoded-len"], workspace = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-balances.workspace = true
pallet-session.workspace = true
pallet-timestamp.workspace = true
sp-consensus-aura.workspace = true
sp-io.workspace = true
sp-runtime.workspace = true
sp-tracing.workspace = true
sp-tracing.default-features = true
sp-core.workspace = true
cumulus-pallet-parachain-system.workspace = true
cumulus-pallet-xcmp-queue.workspace = true
pallet-collator-selection.workspace = true
parachain-info.workspace = true
cumulus-primitives-core.workspace = true
cumulus-primitives-parachain-inherent.workspace = true
cumulus-test-relay-sproof-builder.workspace = true
xcm.workspace = true
xcm-executor.workspace = true
pallet-xcm.workspace = true
polkadot-parachain-primitives.workspace = true

[dev-dependencies]
hex-literal = { workspace = true, default-features = true }

[build-dependencies]
substrate-wasm-builder.workspace = true
substrate-wasm-builder.default-features = true

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-parachain-inherent/std",
	"cumulus-test-relay-sproof-builder/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-collator-selection/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"polkadot-parachain-primitives/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"xcm-executor/std",
	"xcm/std",
	"substrate-wasm-builder/std"
]
runtime-benchmarks = [
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-primitives-parachain-inherent/runtime-benchmarks",
	"cumulus-test-relay-sproof-builder/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collator-selection/runtime-benchmarks",
	"pallet-session/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"sp-consensus-aura/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"parachain-info/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"substrate-wasm-builder/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"cumulus-primitives-parachain-inherent/try-runtime",
	"cumulus-test-relay-sproof-builder/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-collator-selection/try-runtime",
	"pallet-session/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-xcm/try-runtime",
	"polkadot-parachain-primitives/try-runtime",
	"sp-consensus-aura/try-runtime",
	"sp-runtime/try-runtime",
	"parachain-info/try-runtime",
	"xcm-executor/try-runtime",
	"sp-io/try-runtime",
	"substrate-wasm-builder/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
