[package]
name = "pallet-offences-benchmarking"
version = "37.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME offences pallet benchmarking (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame-benchmarking.workspace = true
frame-election-provider-support.workspace = true
frame-support.workspace = true
frame-system.workspace = true
pallet-babe.workspace = true
pallet-balances.workspace = true
pallet-grandpa.workspace = true
pallet-im-online.workspace = true
pallet-offences.workspace = true
pallet-session.workspace = true
pallet-staking.workspace = true
sp-runtime.workspace = true
sp-staking.workspace = true
log = { workspace = true }

[dev-dependencies]
pallet-staking-reward-curve = { default-features = true, path = "../../staking/reward-curve" }
pallet-timestamp = { default-features = true, path = "../../timestamp" }
sp-core = { default-features = true, path = "../../../primitives/core" }
sp-io = { default-features = true, path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking-reward-curve/std"
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-session/runtime-benchmarks",
	"pallet-staking-reward-curve/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"frame-benchmarking/try-runtime",
	"frame-election-provider-support/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-staking-reward-curve/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
	"sp-staking/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime"
]
