[package]
name = "polkadot-availability-bitfield-distribution"
version = "17.0.0"
description = "Polkadot Bitfiled Distribution subsystem, which gossips signed availability bitfields used to compactly determine which backed candidates are available or not based on a 2/3+ quorum. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
always-assert = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
gum.workspace = true
gum.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-node-network-protocol.workspace = true
polkadot-node-network-protocol.default-features = true
rand = { workspace = true, default-features = true }

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
bitvec = { features = ["alloc"], workspace = true }
sp-core = { default-features = true, path = "../../../../substrate/primitives/core" }
sp-application-crypto = { default-features = true, path = "../../../../substrate/primitives/application-crypto" }
sp-authority-discovery = { default-features = true, path = "../../../../substrate/primitives/authority-discovery" }
sp-keystore = { default-features = true, path = "../../../../substrate/primitives/keystore" }
sp-keyring = { default-features = true, path = "../../../../substrate/primitives/keyring" }
maplit = { workspace = true }
log = { workspace = true, default-features = true }
env_logger = { workspace = true }
assert_matches = { workspace = true }
rand_chacha = { workspace = true, default-features = true }

[features]
std = [
	"bitvec/std",
	"log/std",
	"polkadot-node-network-protocol/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-network-protocol/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-primitives/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-keyring/try-runtime",
	"gum/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
