[package]
name = "sc-rpc-api"
version = "0.43.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate RPC interfaces. (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
scale-info = { features = ["derive"], workspace = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-mixnet.workspace = true
sc-mixnet.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-rpc.workspace = true
sp-rpc.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-version.workspace = true
sp-version.default-features = true
jsonrpsee = { features = ["client-core", "macros", "server-core"], workspace = true }

[features]
std = [
	"sc-chain-spec/std",
	"sc-mixnet/std",
	"sc-transaction-pool-api/std",
	"scale-info/std",
	"sp-rpc/std"
]
runtime-benchmarks = [
	"sc-chain-spec/runtime-benchmarks",
	"sc-mixnet/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-rpc/runtime-benchmarks"
]
try-runtime = [
	"sc-chain-spec/try-runtime",
	"sc-mixnet/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-runtime/try-runtime",
	"sp-version/try-runtime",
	"sp-core/try-runtime",
	"sp-rpc/try-runtime"
]
