[package]
name = "node-testing"
version = "3.0.0"
authors.workspace = true
description = "Test utilities for Substrate node. (polkadot v1.15.0)"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
fs_extra = { workspace = true }
futures = { workspace = true }
log = { workspace = true, default-features = true }
tempfile = { workspace = true }
frame-metadata-hash-extension.workspace = true
frame-metadata-hash-extension.default-features = true
frame-system.workspace = true
frame-system.default-features = true
node-cli.workspace = true
node-primitives.workspace = true
node-primitives.default-features = true
kitchensink-runtime.workspace = true
pallet-asset-conversion.workspace = true
pallet-asset-conversion.default-features = true
pallet-assets.workspace = true
pallet-assets.default-features = true
pallet-asset-conversion-tx-payment.workspace = true
pallet-asset-conversion-tx-payment.default-features = true
pallet-asset-tx-payment.workspace = true
pallet-asset-tx-payment.default-features = true
pallet-skip-feeless-payment.workspace = true
pallet-skip-feeless-payment.default-features = true
sc-block-builder.workspace = true
sc-block-builder.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-client-db = { features = ["rocksdb"], workspace = true, default-features = true }
sc-consensus.workspace = true
sc-consensus.default-features = true
sc-executor.workspace = true
sc-executor.default-features = true
sc-service = { features = ["rocksdb", "test-helpers"], workspace = true, default-features = true }
sp-api.workspace = true
sp-api.default-features = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-crypto-hashing.workspace = true
sp-crypto-hashing.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-io.workspace = true
sp-io.default-features = true
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-timestamp.workspace = true
substrate-test-client.workspace = true

[features]
std = [
	"log/std",
	"sc-block-builder/std",
	"sc-client-api/std",
	"sc-client-db/std",
	"sc-consensus/std",
	"sc-service/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"sp-timestamp/std",
	"node-cli/std",
	"substrate-test-client/std"
]
runtime-benchmarks = [
	"frame-metadata-hash-extension/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"kitchensink-runtime/runtime-benchmarks",
	"node-primitives/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-asset-conversion-tx-payment/runtime-benchmarks",
	"pallet-asset-tx-payment/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-skip-feeless-payment/runtime-benchmarks",
	"sc-block-builder/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-executor/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"node-cli/runtime-benchmarks",
	"substrate-test-client/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"frame-metadata-hash-extension/try-runtime",
	"frame-system/try-runtime",
	"kitchensink-runtime/try-runtime",
	"node-primitives/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-asset-conversion-tx-payment/try-runtime",
	"pallet-asset-tx-payment/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-skip-feeless-payment/try-runtime",
	"sc-block-builder/try-runtime",
	"sc-client-api/try-runtime",
	"sc-client-db/try-runtime",
	"sc-consensus/try-runtime",
	"sc-executor/try-runtime",
	"sc-service/try-runtime",
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-inherents/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"sp-timestamp/try-runtime",
	"node-cli/try-runtime",
	"substrate-test-client/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime"
]
