[package]
name = "mmr-gadget"
version = "39.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
description = "MMR Client gadget for substrate (polkadot v1.15.0)"
homepage = "https://substrate.io"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { workspace = true, default-features = true }
futures = { workspace = true }
log = { workspace = true, default-features = true }
sp-api.workspace = true
sp-api.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sp-consensus-beefy.workspace = true
sp-consensus-beefy.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-mmr-primitives.workspace = true
sp-mmr-primitives.default-features = true
sc-offchain.workspace = true
sc-offchain.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[dev-dependencies]
parking_lot = { workspace = true, default-features = true }
sc-block-builder = { default-features = true, path = "../block-builder" }
sp-tracing = { default-features = true, path = "../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
tokio = { workspace = true, default-features = true }

[features]
std = [
	"log/std",
	"sc-block-builder/std",
	"sc-client-api/std",
	"sc-offchain/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-block-builder/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-offchain/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-mmr-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sc-block-builder/try-runtime",
	"sc-client-api/try-runtime",
	"sc-offchain/try-runtime",
	"sp-api/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-consensus-beefy/try-runtime",
	"sp-mmr-primitives/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sp-core/try-runtime"
]
