[package]
name = "substrate-cli-test-utils"
description = "CLI testing utilities (polkadot v1.15.0)"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
substrate-rpc-client.workspace = true
substrate-rpc-client.default-features = true
sp-rpc.workspace = true
sp-rpc.default-features = true
assert_cmd = { workspace = true }
nix = { features = ["signal"], workspace = true }
regex = { workspace = true }
tokio = { features = ["full"], workspace = true, default-features = true }
node-primitives.workspace = true
node-primitives.default-features = true
node-cli.workspace = true
sc-cli.workspace = true
sc-cli.default-features = true
sc-service.workspace = true
sc-service.default-features = true
futures = { workspace = true }

[features]
try-runtime = [
	"node-cli/try-runtime",
	"node-primitives/try-runtime",
	"sc-cli/try-runtime",
	"sc-service/try-runtime",
	"substrate-rpc-client/try-runtime",
	"sp-rpc/try-runtime"
]
std = [
	"sc-cli/std",
	"sc-service/std",
	"sp-rpc/std",
	"node-cli/std",
	"substrate-rpc-client/std"
]
runtime-benchmarks = [
	"node-primitives/runtime-benchmarks",
	"sc-cli/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"node-cli/runtime-benchmarks",
	"substrate-rpc-client/runtime-benchmarks",
	"sp-rpc/runtime-benchmarks"
]
