[package]
name = "sc-consensus-grandpa"
version = "0.29.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Integration of the GRANDPA finality gadget into substrate. (polkadot v1.15.0)"
documentation = "https://docs.rs/sc-consensus-grandpa"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ahash = { workspace = true }
array-bytes = { workspace = true, default-features = true }
async-trait = { workspace = true }
dyn-clone = { workspace = true }
finality-grandpa = { features = ["derive-codec"], workspace = true, default-features = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
codec = { features = ["derive"], workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
rand = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }
fork-tree.workspace = true
fork-tree.default-features = true
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
sc-block-builder.workspace = true
sc-block-builder.default-features = true
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sc-consensus.workspace = true
sc-consensus.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sc-network-gossip.workspace = true
sc-network-gossip.default-features = true
sc-network-common.workspace = true
sc-network-common.default-features = true
sc-network-sync.workspace = true
sc-network-sync.default-features = true
sc-network-types.workspace = true
sc-network-types.default-features = true
sc-telemetry.workspace = true
sc-telemetry.default-features = true
sc-utils.workspace = true
sc-utils.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-application-crypto.workspace = true
sp-application-crypto.default-features = true
sp-arithmetic.workspace = true
sp-arithmetic.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-crypto-hashing.workspace = true
sp-crypto-hashing.default-features = true
sp-consensus-grandpa.workspace = true
sp-consensus-grandpa.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[dev-dependencies]
assert_matches = { workspace = true }
finality-grandpa = { features = ["derive-codec", "test-helpers"], workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
tokio = { workspace = true, default-features = true }
sc-network = { default-features = true, path = "../../network" }
sc-network-test = { path = "../../network/test" }
sp-keyring = { default-features = true, path = "../../../primitives/keyring" }
sp-tracing = { default-features = true, path = "../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }

[features]
std = [
	"fork-tree/std",
	"log/std",
	"sc-block-builder/std",
	"sc-chain-spec/std",
	"sc-client-api/std",
	"sc-consensus/std",
	"sc-network/std",
	"sc-network-common/std",
	"sc-network-gossip/std",
	"sc-network-sync/std",
	"sc-network-test/std",
	"sc-network-types/std",
	"sc-telemetry/std",
	"sc-transaction-pool-api/std",
	"sc-utils/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"prometheus-endpoint/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-block-builder/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-network-common/runtime-benchmarks",
	"sc-network-gossip/runtime-benchmarks",
	"sc-network-sync/runtime-benchmarks",
	"sc-network-test/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-consensus-grandpa/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"sc-block-builder/try-runtime",
	"sc-chain-spec/try-runtime",
	"sc-client-api/try-runtime",
	"sc-consensus/try-runtime",
	"sc-network/try-runtime",
	"sc-network-common/try-runtime",
	"sc-network-gossip/try-runtime",
	"sc-network-sync/try-runtime",
	"sc-network-test/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-consensus-grandpa/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sc-telemetry/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
