[package]
name = "substrate-test-client"
description = "Client testing utilities (polkadot v1.15.0)"
version = "2.0.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { workspace = true, default-features = true }
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
futures = { workspace = true }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-client-db = { features = ["test-helpers"], workspace = true }
sc-consensus.workspace = true
sc-consensus.default-features = true
sc-executor.workspace = true
sc-executor.default-features = true
sc-offchain.workspace = true
sc-offchain.default-features = true
sc-service = { features = ["test-helpers"], workspace = true }
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
tokio = { features = ["sync"], workspace = true, default-features = true }

[features]
std = [
	"sc-client-api/std",
	"sc-client-db/std",
	"sc-consensus/std",
	"sc-offchain/std",
	"sc-service/std",
	"sp-blockchain/std",
	"sp-consensus/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-executor/runtime-benchmarks",
	"sc-offchain/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-client-db/try-runtime",
	"sc-consensus/try-runtime",
	"sc-executor/try-runtime",
	"sc-offchain/try-runtime",
	"sc-service/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
