[package]
name = "test-parachain-adder-collator"
description = "Collator for the adder test parachain (polkadot v1.15.0)"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[dependencies]
codec = { features = ["derive"], workspace = true }
clap = { features = ["derive"], workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
test-parachain-adder.workspace = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-cli.workspace = true
polkadot-cli.default-features = true
polkadot-service = { features = ["rococo-native"], workspace = true, default-features = true }
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
sc-cli.workspace = true
sc-cli.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sc-service.workspace = true
sc-service.default-features = true

[dev-dependencies]
polkadot-parachain-primitives = { default-features = true, path = "../../.." }
polkadot-test-service = { path = "../../../../node/test/service" }
polkadot-node-core-pvf = { features = ["test-utils"], default-features = true, path = "../../../../node/core/pvf" }

substrate-test-utils = { path = "../../../../../substrate/test-utils" }
sc-service = { default-features = true, path = "../../../../../substrate/client/service" }
sp-keyring = { default-features = true, path = "../../../../../substrate/primitives/keyring" }

tokio = { features = ["macros"], workspace = true, default-features = true }

[features]
std = [
	"log/std",
	"codec/std",
	"polkadot-cli/std",
	"polkadot-node-core-pvf/std",
	"polkadot-node-primitives/std",
	"polkadot-service/std",
	"polkadot-test-service/std",
	"sc-cli/std",
	"sc-service/std",
	"substrate-test-utils/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-cli/runtime-benchmarks",
	"polkadot-node-core-pvf/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
	"polkadot-test-service/runtime-benchmarks",
	"sc-cli/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"substrate-test-utils/runtime-benchmarks",
	"test-parachain-adder/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"polkadot-cli/try-runtime",
	"polkadot-node-core-pvf/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-parachain-primitives/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-service/try-runtime",
	"polkadot-test-service/try-runtime",
	"sc-cli/try-runtime",
	"sc-service/try-runtime",
	"sp-keyring/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"substrate-test-utils/try-runtime",
	"test-parachain-adder/try-runtime",
	"sp-core/try-runtime"
]
