[package]
name = "pallet-bags-list-remote-tests"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME pallet bags list remote test (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
pallet-staking.workspace = true
pallet-staking.default-features = true
pallet-bags-list = { features = ["fuzz"], workspace = true, default-features = true }
frame-election-provider-support.workspace = true
frame-election-provider-support.default-features = true
frame-system.workspace = true
frame-system.default-features = true
frame-support.workspace = true
frame-support.default-features = true
sp-storage.workspace = true
sp-storage.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-tracing.workspace = true
sp-tracing.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-std.workspace = true
sp-std.default-features = true
remote-externalities.workspace = true
remote-externalities.default-features = true

# others
log = { workspace = true, default-features = true }

[features]
std = [
	"remote-externalities/std",
	"log/std"
]
runtime-benchmarks = [
	"frame-election-provider-support/runtime-benchmarks",
	"remote-externalities/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"remote-externalities/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-bags-list/try-runtime",
	"pallet-staking/try-runtime",
	"sp-runtime/try-runtime",
	"sp-core/try-runtime"
]
