[package]
name = "westend-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Westend emulated chain (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[dependencies]
sp-core.workspace = true
sp-runtime.workspace = true
sp-authority-discovery.workspace = true
sp-consensus-babe.workspace = true
sp-consensus-beefy.workspace = true
sp-consensus-beefy.default-features = true
sc-consensus-grandpa.workspace = true
pallet-staking.workspace = true
polkadot-primitives.workspace = true
westend-runtime-constants.workspace = true
westend-runtime.workspace = true
xcm.workspace = true
xcm-runtime-apis.workspace = true
parachains-common.workspace = true
parachains-common.default-features = true
emulated-integration-tests-common.workspace = true

[features]
std = [
	"emulated-integration-tests-common/std",
	"pallet-staking/std",
	"polkadot-primitives/std",
	"sc-consensus-grandpa/std",
	"sp-authority-discovery/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-runtime/std",
	"xcm/std",
	"westend-runtime-constants/std",
	"xcm-runtime-apis/std"
]
runtime-benchmarks = [
	"emulated-integration-tests-common/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-consensus-grandpa/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"westend-runtime/runtime-benchmarks",
	"westend-runtime-constants/runtime-benchmarks",
	"xcm-runtime-apis/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"emulated-integration-tests-common/try-runtime",
	"pallet-staking/try-runtime",
	"parachains-common/try-runtime",
	"polkadot-primitives/try-runtime",
	"sc-consensus-grandpa/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-consensus-beefy/try-runtime",
	"sp-runtime/try-runtime",
	"westend-runtime/try-runtime",
	"westend-runtime-constants/try-runtime",
	"xcm-runtime-apis/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
