[package]
name = "polkadot-approval-distribution"
version = "17.0.0"
description = "Polkadot Approval Distribution subsystem for the distribution of assignments and approvals for approval checks on candidates over the network. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
polkadot-node-metrics.workspace = true
polkadot-node-metrics.default-features = true
polkadot-node-network-protocol.workspace = true
polkadot-node-network-protocol.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-jaeger.workspace = true
polkadot-node-jaeger.default-features = true
rand = { workspace = true, default-features = true }
itertools = { workspace = true }

futures = { workspace = true }
futures-timer = { workspace = true }
gum.workspace = true
gum.default-features = true
bitvec = { features = ["alloc"], workspace = true }

[dev-dependencies]
sp-authority-discovery = { default-features = true, path = "../../../../substrate/primitives/authority-discovery" }
sp-core = { features = ["std"], default-features = true, path = "../../../../substrate/primitives/core" }

polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }

assert_matches = { workspace = true }
schnorrkel = { workspace = true }
# rand_core should match schnorrkel
rand_core = { workspace = true }
rand_chacha = { workspace = true, default-features = true }
env_logger = { workspace = true }
log = { workspace = true, default-features = true }

[features]
std = [
	"bitvec/std",
	"log/std",
	"polkadot-node-jaeger/std",
	"polkadot-node-metrics/std",
	"polkadot-node-network-protocol/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-primitives-test-helpers/std",
	"rand_core/std",
	"schnorrkel/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-jaeger/runtime-benchmarks",
	"polkadot-node-metrics/runtime-benchmarks",
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-jaeger/try-runtime",
	"polkadot-node-metrics/try-runtime",
	"polkadot-node-network-protocol/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"sp-authority-discovery/try-runtime",
	"gum/try-runtime",
	"sp-core/try-runtime"
]
