[package]
name = "parachain-template-node"
description = "A parachain node template built with Substrate and Cumulus, part of Polkadot Sdk. (polkadot v1.15.0)"
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
build = "build.rs"

# [[bin]]
# name = "parachain-template-node"

[dependencies]
clap = { features = ["derive"], workspace = true }
log = { workspace = true, default-features = true }
codec = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
jsonrpsee = { features = ["server"], workspace = true }
futures = { workspace = true }
serde_json = { workspace = true, default-features = true }
docify = { workspace = true }
parachain-template-runtime.workspace = true
frame-benchmarking.workspace = true
frame-benchmarking.default-features = true
frame-benchmarking-cli.workspace = true
frame-benchmarking-cli.default-features = true
pallet-transaction-payment-rpc.workspace = true
pallet-transaction-payment-rpc.default-features = true
sc-basic-authorship.workspace = true
sc-basic-authorship.default-features = true
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-cli.workspace = true
sc-cli.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-offchain.workspace = true
sc-offchain.default-features = true
sc-consensus.workspace = true
sc-consensus.default-features = true
sc-executor.workspace = true
sc-executor.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sc-network-sync.workspace = true
sc-network-sync.default-features = true
sc-rpc.workspace = true
sc-rpc.default-features = true
sc-service.workspace = true
sc-service.default-features = true
sc-sysinfo.workspace = true
sc-sysinfo.default-features = true
sc-telemetry.workspace = true
sc-telemetry.default-features = true
sc-tracing.workspace = true
sc-tracing.default-features = true
sc-transaction-pool.workspace = true
sc-transaction-pool.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus-aura.workspace = true
sp-consensus-aura.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-io.workspace = true
sp-io.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-timestamp.workspace = true
sp-timestamp.default-features = true
substrate-frame-rpc-system.workspace = true
substrate-frame-rpc-system.default-features = true
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
polkadot-cli = { features = ["rococo-native"], workspace = true, default-features = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
xcm.workspace = true
cumulus-client-cli.workspace = true
cumulus-client-cli.default-features = true
cumulus-client-collator.workspace = true
cumulus-client-collator.default-features = true
cumulus-client-consensus-aura.workspace = true
cumulus-client-consensus-aura.default-features = true
cumulus-client-consensus-common.workspace = true
cumulus-client-consensus-common.default-features = true
cumulus-client-consensus-proposer.workspace = true
cumulus-client-consensus-proposer.default-features = true
cumulus-client-service.workspace = true
cumulus-client-service.default-features = true
cumulus-primitives-core.workspace = true
cumulus-primitives-core.default-features = true
cumulus-primitives-parachain-inherent.workspace = true
cumulus-primitives-parachain-inherent.default-features = true
cumulus-relay-chain-interface.workspace = true
cumulus-relay-chain-interface.default-features = true
color-print = { workspace = true }

[build-dependencies]
substrate-build-script-utils.workspace = true
substrate-build-script-utils.default-features = true

[features]
default = []
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"parachain-template-runtime/runtime-benchmarks",
	"polkadot-cli/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"cumulus-client-cli/runtime-benchmarks",
	"cumulus-client-collator/runtime-benchmarks",
	"cumulus-client-consensus-aura/runtime-benchmarks",
	"cumulus-client-consensus-common/runtime-benchmarks",
	"cumulus-client-consensus-proposer/runtime-benchmarks",
	"cumulus-client-service/runtime-benchmarks",
	"cumulus-primitives-parachain-inherent/runtime-benchmarks",
	"cumulus-relay-chain-interface/runtime-benchmarks",
	"pallet-transaction-payment-rpc/runtime-benchmarks",
	"sc-basic-authorship/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sc-cli/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-executor/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-network-sync/runtime-benchmarks",
	"sc-offchain/runtime-benchmarks",
	"sc-rpc/runtime-benchmarks",
	"sc-sysinfo/runtime-benchmarks",
	"sc-tracing/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-aura/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"substrate-frame-rpc-system/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"parachain-template-runtime/try-runtime",
	"polkadot-cli/try-runtime",
	"sp-runtime/try-runtime",
	"cumulus-client-cli/try-runtime",
	"cumulus-client-collator/try-runtime",
	"cumulus-client-consensus-aura/try-runtime",
	"cumulus-client-consensus-common/try-runtime",
	"cumulus-client-consensus-proposer/try-runtime",
	"cumulus-client-service/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"cumulus-primitives-parachain-inherent/try-runtime",
	"frame-benchmarking/try-runtime",
	"frame-benchmarking-cli/try-runtime",
	"pallet-transaction-payment-rpc/try-runtime",
	"polkadot-primitives/try-runtime",
	"sc-basic-authorship/try-runtime",
	"sc-chain-spec/try-runtime",
	"sc-cli/try-runtime",
	"sc-client-api/try-runtime",
	"sc-consensus/try-runtime",
	"sc-executor/try-runtime",
	"sc-network/try-runtime",
	"sc-network-sync/try-runtime",
	"sc-offchain/try-runtime",
	"sc-rpc/try-runtime",
	"sc-service/try-runtime",
	"sc-sysinfo/try-runtime",
	"sc-tracing/try-runtime",
	"sc-transaction-pool/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus-aura/try-runtime",
	"sp-timestamp/try-runtime",
	"substrate-frame-rpc-system/try-runtime",
	"cumulus-relay-chain-interface/try-runtime",
	"sc-telemetry/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime",
	"sp-keystore/try-runtime"
]
std = [
	"cumulus-client-cli/std",
	"cumulus-client-collator/std",
	"cumulus-client-consensus-aura/std",
	"cumulus-client-consensus-common/std",
	"cumulus-client-consensus-proposer/std",
	"cumulus-client-service/std",
	"cumulus-relay-chain-interface/std",
	"frame-benchmarking-cli/std",
	"log/std",
	"pallet-transaction-payment-rpc/std",
	"polkadot-cli/std",
	"sc-basic-authorship/std",
	"sc-chain-spec/std",
	"sc-cli/std",
	"sc-client-api/std",
	"sc-consensus/std",
	"sc-network/std",
	"sc-network-sync/std",
	"sc-offchain/std",
	"sc-rpc/std",
	"sc-service/std",
	"sc-sysinfo/std",
	"sc-telemetry/std",
	"sc-tracing/std",
	"sc-transaction-pool/std",
	"sc-transaction-pool-api/std",
	"sp-blockchain/std",
	"xcm/std",
	"substrate-frame-rpc-system/std",
	"prometheus-endpoint/std"
]
