[package]
name = "polkadot-node-subsystem-types"
description = "Subsystem traits and message definitions (polkadot v1.15.0)"
version = "17.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
derive_more = { workspace = true, default-features = true }
fatality = { workspace = true }
futures = { workspace = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-network-protocol.workspace = true
polkadot-node-network-protocol.default-features = true
polkadot-statement-table.workspace = true
polkadot-statement-table.default-features = true
polkadot-node-jaeger.workspace = true
polkadot-node-jaeger.default-features = true
orchestra = { features = ["futures_channel"], workspace = true }
sc-network.workspace = true
sc-network.default-features = true
sc-network-types.workspace = true
sc-network-types.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus-babe.workspace = true
sp-consensus-babe.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-authority-discovery.workspace = true
sp-authority-discovery.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
smallvec = { workspace = true, default-features = true }
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
thiserror = { workspace = true }
async-trait = { workspace = true }
bitvec = { features = ["alloc"], workspace = true }

[features]
std = [
	"bitvec/std",
	"polkadot-node-jaeger/std",
	"polkadot-node-network-protocol/std",
	"polkadot-node-primitives/std",
	"polkadot-statement-table/std",
	"sc-client-api/std",
	"sc-network/std",
	"sc-network-types/std",
	"sc-transaction-pool-api/std",
	"sp-blockchain/std",
	"prometheus-endpoint/std"
]
runtime-benchmarks = [
	"polkadot-node-jaeger/runtime-benchmarks",
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-statement-table/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-network-protocol/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-primitives/try-runtime",
	"sc-client-api/try-runtime",
	"sc-network/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-runtime/try-runtime",
	"polkadot-node-jaeger/try-runtime",
	"polkadot-statement-table/try-runtime"
]
