[package]
name = "xcm-executor-integration-tests"
description = "Integration tests for the XCM Executor (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "1.0.0"
publish = false

[lints]
workspace = true

[dependencies]
codec = { workspace = true, default-features = true }
frame-support.workspace = true
frame-system.workspace = true
frame-system.default-features = true
futures = { workspace = true }
pallet-transaction-payment.workspace = true
pallet-transaction-payment.default-features = true
pallet-xcm.workspace = true
pallet-xcm.default-features = true
polkadot-test-client.workspace = true
polkadot-test-runtime.workspace = true
polkadot-test-service.workspace = true
polkadot-service.workspace = true
polkadot-service.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-runtime.workspace = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
xcm.workspace = true
xcm-executor.workspace = true
xcm-executor.default-features = true
sp-tracing.workspace = true
sp-tracing.default-features = true
sp-core.workspace = true
sp-core.default-features = true

[features]
default = ["std"]
std = [
	"frame-support/std",
	"sp-runtime/std",
	"xcm/std",
	"polkadot-service/std",
	"polkadot-test-client/std",
	"polkadot-test-service/std",
	"sp-consensus/std"
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
	"polkadot-test-client/runtime-benchmarks",
	"polkadot-test-runtime/runtime-benchmarks",
	"polkadot-test-service/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-xcm/try-runtime",
	"polkadot-service/try-runtime",
	"polkadot-test-client/try-runtime",
	"polkadot-test-runtime/try-runtime",
	"polkadot-test-service/try-runtime",
	"sp-consensus/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"xcm-executor/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
