[package]
name = "rococo-westend-system-emulated-network"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Rococo<>Westend emulated bridged network (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[dependencies]
emulated-integration-tests-common.workspace = true
rococo-emulated-chain.workspace = true
westend-emulated-chain.workspace = true
westend-emulated-chain.default-features = true
asset-hub-rococo-emulated-chain.workspace = true
asset-hub-westend-emulated-chain.workspace = true
bridge-hub-rococo-emulated-chain.workspace = true
bridge-hub-westend-emulated-chain.workspace = true
penpal-emulated-chain.workspace = true

[features]
std = [
	"asset-hub-rococo-emulated-chain/std",
	"asset-hub-westend-emulated-chain/std",
	"bridge-hub-rococo-emulated-chain/std",
	"bridge-hub-westend-emulated-chain/std",
	"emulated-integration-tests-common/std",
	"penpal-emulated-chain/std",
	"rococo-emulated-chain/std",
	"westend-emulated-chain/std"
]
runtime-benchmarks = [
	"asset-hub-rococo-emulated-chain/runtime-benchmarks",
	"asset-hub-westend-emulated-chain/runtime-benchmarks",
	"bridge-hub-rococo-emulated-chain/runtime-benchmarks",
	"bridge-hub-westend-emulated-chain/runtime-benchmarks",
	"emulated-integration-tests-common/runtime-benchmarks",
	"penpal-emulated-chain/runtime-benchmarks",
	"rococo-emulated-chain/runtime-benchmarks",
	"westend-emulated-chain/runtime-benchmarks"
]
try-runtime = [
	"asset-hub-rococo-emulated-chain/try-runtime",
	"asset-hub-westend-emulated-chain/try-runtime",
	"bridge-hub-rococo-emulated-chain/try-runtime",
	"bridge-hub-westend-emulated-chain/try-runtime",
	"emulated-integration-tests-common/try-runtime",
	"penpal-emulated-chain/try-runtime",
	"rococo-emulated-chain/try-runtime",
	"westend-emulated-chain/try-runtime"
]
