[package]
name = "sc-client-db"
version = "0.44.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Client backend that uses RocksDB database as storage. (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true, default-features = true }
hash-db = { workspace = true, default-features = true }
kvdb = { workspace = true }
kvdb-memorydb = { workspace = true }
kvdb-rocksdb = { optional = true, workspace = true }
linked-hash-map = { workspace = true }
log = { workspace = true, default-features = true }
parity-db = { workspace = true }
parking_lot = { workspace = true, default-features = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-state-db.workspace = true
sc-state-db.default-features = true
schnellru = { workspace = true }
sp-arithmetic.workspace = true
sp-arithmetic.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-database.workspace = true
sp-database.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
sp-trie.workspace = true
sp-trie.default-features = true

[dev-dependencies]
criterion = { workspace = true, default-features = true }
kvdb-rocksdb = { workspace = true }
rand = { workspace = true, default-features = true }
tempfile = { workspace = true }
quickcheck = { workspace = true }
kitchensink-runtime = { path = "../../bin/node/runtime" }
sp-tracing = { default-features = true, path = "../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
array-bytes = { workspace = true, default-features = true }

[features]
default = []
test-helpers = []
runtime-benchmarks = [
	"sp-runtime/runtime-benchmarks",
	"kitchensink-runtime/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sc-state-db/runtime-benchmarks"
]
rocksdb = ["kvdb-rocksdb"]
std = [
	"log/std",
	"sc-client-api/std",
	"sc-state-db/std",
	"sp-blockchain/std",
	"substrate-test-runtime-client/std"
]
try-runtime = [
	"kitchensink-runtime/try-runtime",
	"sc-client-api/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"sp-trie/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sp-core/try-runtime",
	"sc-state-db/try-runtime"
]

[[bench]]
name = "state_access"
harness = false

[lib]
bench = false
