[package]
name = "polkadot-node-primitives"
description = "Primitives types for the Node-side (polkadot v1.15.0)"
version = "15.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bounded-vec = { workspace = true }
futures = { workspace = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
codec = { features = ["derive"], workspace = true }
sp-core.workspace = true
sp-core.default-features = true
sp-application-crypto.workspace = true
sp-application-crypto.default-features = true
sp-consensus-babe.workspace = true
sp-consensus-babe.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-maybe-compressed-blob.workspace = true
sp-maybe-compressed-blob.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
polkadot-parachain-primitives.workspace = true
schnorrkel = { workspace = true, default-features = true }
thiserror = { workspace = true }
bitvec = { features = ["alloc"], workspace = true }
serde = { features = ["derive"], workspace = true, default-features = true }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = { version = "0.12.4", default-features = false }

[dev-dependencies]
polkadot-erasure-coding = { default-features = true, path = "../../erasure-coding" }

[features]
std = [
	"bitvec/std",
	"codec/std",
	"polkadot-erasure-coding/std",
	"polkadot-parachain-primitives/std"
]
runtime-benchmarks = [
	"polkadot-erasure-coding/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-parachain-primitives/try-runtime",
	"polkadot-primitives/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-runtime/try-runtime",
	"polkadot-erasure-coding/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
