[package]
name = "polkadot-node-core-parachains-inherent"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Parachains inherent data provider for Polkadot node (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }
gum.workspace = true
gum.default-features = true
thiserror = { workspace = true }
async-trait = { workspace = true }
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-overseer.workspace = true
polkadot-overseer.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true

[features]
std = [
	"polkadot-overseer/std",
	"sp-blockchain/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-overseer/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-subsystem/try-runtime",
	"polkadot-overseer/try-runtime",
	"polkadot-primitives/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-inherents/try-runtime",
	"gum/try-runtime"
]
