[package]
name = "sp-consensus-aura"
version = "0.40.0"
authors.workspace = true
description = "Primitives for Aura consensus (polkadot v1.15.0)"
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { optional = true, workspace = true }
codec = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
sp-api.workspace = true
sp-application-crypto.workspace = true
sp-consensus-slots.workspace = true
sp-inherents.workspace = true
sp-runtime.workspace = true
sp-timestamp.workspace = true

[features]
default = ["std"]
std = [
	"async-trait",
	"codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-consensus-slots/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-timestamp/std",
]

# Serde support without relying on std features.
serde = [
	"scale-info/serde",
	"sp-application-crypto/serde",
	"sp-consensus-slots/serde",
	"sp-runtime/serde",
]
runtime-benchmarks = [
	"sp-api/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks"
]
try-runtime = [
	"sp-api/try-runtime",
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-timestamp/try-runtime",
	"sp-consensus-slots/try-runtime",
	"sp-application-crypto/try-runtime"
]
