[package]
name = "pallet-babe"
version = "37.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Consensus extension module for BABE consensus. Collects on-chain randomness from VRF outputs and manages epoch transitions. (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
log = { workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
frame-benchmarking = { optional = true, workspace = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-authorship.workspace = true
pallet-session.workspace = true
pallet-timestamp.workspace = true
sp-application-crypto = { features = ["serde"], workspace = true }
sp-consensus-babe = { features = ["serde"], workspace = true }
sp-core = { features = ["serde"], workspace = true }
sp-io.workspace = true
sp-runtime = { features = ["serde"], workspace = true }
sp-session.workspace = true
sp-staking = { features = ["serde"], workspace = true }

[dev-dependencies]
frame-election-provider-support = { default-features = true, path = "../election-provider-support" }
pallet-balances = { default-features = true, path = "../balances" }
pallet-offences = { default-features = true, path = "../offences" }
pallet-staking = { default-features = true, path = "../staking" }
pallet-staking-reward-curve = { default-features = true, path = "../staking/reward-curve" }
sp-core = { default-features = true, path = "../../primitives/core" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"scale-info/std",
	"sp-application-crypto/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"pallet-staking-reward-curve/std"
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-authorship/runtime-benchmarks",
	"pallet-session/runtime-benchmarks",
	"pallet-staking-reward-curve/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-session/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-session/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
	"frame-election-provider-support/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-staking/try-runtime",
	"frame-benchmarking?/try-runtime",
	"pallet-staking-reward-curve/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-session/try-runtime",
	"sp-staking/try-runtime",
	"sp-io/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime"
]
