[package]
name = "polkadot-node-metrics"
description = "Subsystem metric helpers (polkadot v1.15.0)"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }
gum.workspace = true
gum.default-features = true

metered = { features = ["futures_channel"], workspace = true }
sc-service.workspace = true
sc-service.default-features = true
sc-cli.workspace = true
sc-cli.default-features = true
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
sc-tracing.workspace = true
sc-tracing.default-features = true
codec = { workspace = true, default-features = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
bs58 = { features = ["alloc"], workspace = true, default-features = true }
log = { workspace = true, default-features = true }

[dev-dependencies]
assert_cmd = { workspace = true }
tempfile = { workspace = true }
hyper-util = { features = ["client-legacy", "tokio"], workspace = true }
hyper = { workspace = true }
http-body-util = { workspace = true }
tokio = { workspace = true, default-features = true }
polkadot-test-service = { features = ["runtime-metrics"], path = "../test/service" }
substrate-test-utils = { path = "../../../substrate/test-utils" }
sc-service = { default-features = true, path = "../../../substrate/client/service" }
sp-keyring = { default-features = true, path = "../../../substrate/primitives/keyring" }
prometheus-parse = { workspace = true }

[features]
default = []
runtime-metrics = []
runtime-benchmarks = [
	"polkadot-primitives/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"polkadot-test-service/runtime-benchmarks",
	"sc-cli/runtime-benchmarks",
	"sc-tracing/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"substrate-test-utils/runtime-benchmarks",
	"gum/runtime-benchmarks"
]
std = [
	"log/std",
	"polkadot-test-service/std",
	"sc-cli/std",
	"sc-service/std",
	"sc-tracing/std",
	"prometheus-endpoint/std",
	"substrate-test-utils/std",
	"gum/std"
]
try-runtime = [
	"polkadot-primitives/try-runtime",
	"polkadot-test-service/try-runtime",
	"sc-cli/try-runtime",
	"sc-service/try-runtime",
	"sc-tracing/try-runtime",
	"sp-keyring/try-runtime",
	"substrate-test-utils/try-runtime",
	"gum/try-runtime"
]
