[package]
name = "polkadot-node-core-runtime-api"
version = "17.0.0"
description = "Wrapper around the parachain-related runtime APIs (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gum.workspace = true
gum.default-features = true
schnellru = { workspace = true }
sp-consensus-babe.workspace = true
sp-consensus-babe.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-metrics.workspace = true
polkadot-node-metrics.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-types.workspace = true
polkadot-node-subsystem-types.default-features = true

[dev-dependencies]
sp-api = { default-features = true, path = "../../../../substrate/primitives/api" }
sp-core = { default-features = true, path = "../../../../substrate/primitives/core" }
sp-keyring = { default-features = true, path = "../../../../substrate/primitives/keyring" }
async-trait = { workspace = true }
futures = { features = ["thread-pool"], workspace = true }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-node-primitives = { default-features = true, path = "../../primitives" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }

[features]
std = [
	"polkadot-node-metrics/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-types/std",
	"polkadot-primitives-test-helpers/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-metrics/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-types/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-metrics/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-types/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"sp-api/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-keyring/try-runtime",
	"gum/try-runtime",
	"sp-core/try-runtime"
]
