[package]
name = "emulated-integration-tests-common"
version = "13.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Common resources for integration testing with xcm-emulator (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
paste = { workspace = true, default-features = true }
sp-consensus-beefy.workspace = true
sp-consensus-beefy.default-features = true
sc-consensus-grandpa.workspace = true
sc-consensus-grandpa.default-features = true
sp-authority-discovery.workspace = true
sp-authority-discovery.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
frame-support.workspace = true
frame-support.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-consensus-babe.workspace = true
sp-consensus-babe.default-features = true
pallet-assets.workspace = true
pallet-assets.default-features = true
pallet-balances.workspace = true
pallet-balances.default-features = true
pallet-message-queue.workspace = true
pallet-message-queue.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-parachain-primitives.workspace = true
polkadot-parachain-primitives.default-features = true
polkadot-runtime-parachains.workspace = true
polkadot-runtime-parachains.default-features = true
xcm.workspace = true
xcm.default-features = true
pallet-xcm.workspace = true
pallet-xcm.default-features = true
parachains-common.workspace = true
parachains-common.default-features = true
cumulus-primitives-core.workspace = true
cumulus-primitives-core.default-features = true
xcm-emulator.workspace = true
xcm-emulator.default-features = true
cumulus-pallet-xcmp-queue.workspace = true
cumulus-pallet-xcmp-queue.default-features = true
cumulus-pallet-parachain-system.workspace = true
cumulus-pallet-parachain-system.default-features = true
asset-test-utils.workspace = true
asset-test-utils.default-features = true
bp-messages.workspace = true
bp-messages.default-features = true
pallet-bridge-messages.workspace = true
pallet-bridge-messages.default-features = true
bridge-runtime-common.workspace = true
bridge-runtime-common.default-features = true

[features]
std = [
	"codec/std",
	"sc-consensus-grandpa/std",
	"xcm-emulator/std"
]
runtime-benchmarks = [
	"asset-test-utils/runtime-benchmarks",
	"bp-messages/runtime-benchmarks",
	"bridge-runtime-common/runtime-benchmarks",
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"sc-consensus-grandpa/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-emulator/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"asset-test-utils/try-runtime",
	"bp-messages/try-runtime",
	"bridge-runtime-common/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"frame-support/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bridge-messages/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-xcm/try-runtime",
	"parachains-common/try-runtime",
	"polkadot-parachain-primitives/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-runtime-parachains/try-runtime",
	"sc-consensus-grandpa/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-consensus-beefy/try-runtime",
	"sp-runtime/try-runtime",
	"xcm-emulator/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
