[package]
name = "polkadot-node-core-bitfield-signing"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Bitfield signing subsystem for the Polkadot node (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gum.workspace = true
gum.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
wasm-timer = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }

[features]
std = [
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-primitives-test-helpers/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"gum/try-runtime",
	"sp-keystore/try-runtime"
]
