[package]
name = "polkadot-node-core-av-store"
description = "The Availability Store subsystem. Wrapper over the DB that stores availability data and chunks. (polkadot v1.15.0)"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }
kvdb = { workspace = true }
thiserror = { workspace = true }
gum.workspace = true
gum.default-features = true
bitvec = { workspace = true, default-features = true }

codec = { features = ["derive"], workspace = true, default-features = true }
polkadot-erasure-coding.workspace = true
polkadot-erasure-coding.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-overseer.workspace = true
polkadot-overseer.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
sp-consensus.workspace = true
polkadot-node-jaeger.workspace = true
polkadot-node-jaeger.default-features = true

[dev-dependencies]
log = { workspace = true, default-features = true }
env_logger = { workspace = true }
assert_matches = { workspace = true }
kvdb-memorydb = { workspace = true }

sp-core = { default-features = true, path = "../../../../substrate/primitives/core" }
polkadot-node-subsystem-util = { default-features = true, path = "../../subsystem-util" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { default-features = true, path = "../../../../substrate/primitives/keyring" }
parking_lot = { workspace = true, default-features = true }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }

[features]
std = [
	"log/std",
	"polkadot-erasure-coding/std",
	"polkadot-node-jaeger/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-overseer/std",
	"polkadot-primitives-test-helpers/std",
	"sp-consensus/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-erasure-coding/runtime-benchmarks",
	"polkadot-node-jaeger/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-overseer/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"polkadot-erasure-coding/try-runtime",
	"polkadot-node-jaeger/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-overseer/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"sp-consensus/try-runtime",
	"sp-keyring/try-runtime",
	"gum/try-runtime",
	"sp-core/try-runtime"
]
