[package]
name = "sc-consensus-beefy-rpc"
version = "23.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
description = "RPC for the BEEFY Client gadget for substrate (polkadot v1.15.0)"
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true, default-features = true }
futures = { workspace = true }
jsonrpsee = { features = ["client-core", "macros", "server-core"], workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
thiserror = { workspace = true }
sc-consensus-beefy.workspace = true
sc-consensus-beefy.default-features = true
sp-consensus-beefy.workspace = true
sp-consensus-beefy.default-features = true
sc-rpc.workspace = true
sc-rpc.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-application-crypto.workspace = true
sp-application-crypto.default-features = true

[dev-dependencies]
serde_json = { workspace = true, default-features = true }
sc-rpc = { features = ["test-helpers"], default-features = true, path = "../../../rpc" }
substrate-test-runtime-client = { path = "../../../../test-utils/runtime/client" }
tokio = { features = ["macros"], workspace = true, default-features = true }

[features]
std = [
	"log/std",
	"sc-consensus-beefy/std",
	"sc-rpc/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-consensus-beefy/runtime-benchmarks",
	"sc-rpc/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sc-consensus-beefy/try-runtime",
	"sc-rpc/try-runtime",
	"sp-consensus-beefy/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime"
]
