[package]
name = "sc-cli"
version = "0.46.0"
authors.workspace = true
description = "Substrate CLI interface. (polkadot v1.15.0)"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { workspace = true, default-features = true }
chrono = { workspace = true }
clap = { features = ["derive", "string", "wrap_help"], workspace = true }
fdlimit = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
libp2p-identity = { features = ["ed25519", "peerid"], workspace = true }
log = { workspace = true, default-features = true }
names = { workspace = true }
codec = { workspace = true, default-features = true }
rand = { workspace = true, default-features = true }
regex = { workspace = true }
rpassword = { workspace = true }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }
# personal fork here as workaround for: https://github.com/rust-bitcoin/rust-bip39/pull/64
bip39 = { package = "parity-bip39", version = "2.0.1", features = ["rand"] }
tokio = { features = ["parking_lot", "rt-multi-thread", "signal"], workspace = true, default-features = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-client-db.workspace = true
sc-keystore.workspace = true
sc-keystore.default-features = true
sc-mixnet.workspace = true
sc-mixnet.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sc-service.workspace = true
sc-telemetry.workspace = true
sc-telemetry.default-features = true
sc-tracing.workspace = true
sc-tracing.default-features = true
sc-utils.workspace = true
sc-utils.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-panic-handler.workspace = true
sp-panic-handler.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-version.workspace = true
sp-version.default-features = true

[dev-dependencies]
tempfile = { workspace = true }
futures-timer = { workspace = true }
sp-tracing = { default-features = true, path = "../../primitives/tracing" }

[features]
default = ["rocksdb"]
rocksdb = ["sc-client-db/rocksdb"]
std = [
	"log/std",
	"sc-client-api/std",
	"sc-client-db/std",
	"sc-keystore/std",
	"sc-mixnet/std",
	"sc-network/std",
	"sc-service/std",
	"sc-telemetry/std",
	"sc-tracing/std",
	"sc-utils/std",
	"sp-blockchain/std",
	"sp-panic-handler/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"sc-mixnet/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sc-tracing/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sc-keystore/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-client-db/try-runtime",
	"sc-mixnet/try-runtime",
	"sc-network/try-runtime",
	"sc-service/try-runtime",
	"sc-tracing/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"sp-version/try-runtime",
	"sc-telemetry/try-runtime",
	"sp-core/try-runtime",
	"sc-keystore/try-runtime",
	"sp-keystore/try-runtime"
]
