[package]
name = "bridge-runtime-common"
version = "0.17.0"
description = "Common types and functions that may be used by substrate-based runtimes of all bridged chains (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
static_assertions = { optional = true, workspace = true, default-features = true }
tuplex = { workspace = true }
bp-header-chain.workspace = true
bp-messages.workspace = true
bp-parachains.workspace = true
bp-polkadot-core.workspace = true
bp-relayers.workspace = true
bp-runtime.workspace = true
bp-xcm-bridge-hub.workspace = true
bp-xcm-bridge-hub-router.workspace = true
pallet-bridge-grandpa.workspace = true
pallet-bridge-messages.workspace = true
pallet-bridge-parachains.workspace = true
pallet-bridge-relayers.workspace = true
frame-support.workspace = true
frame-system.workspace = true
pallet-transaction-payment.workspace = true
pallet-utility.workspace = true
sp-io.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true
sp-trie = { optional = true, workspace = true }
xcm.workspace = true
xcm-builder.workspace = true

[dev-dependencies]
bp-test-utils = { path = "../../primitives/test-utils", default-features = false }
pallet-balances = { path = "../../../substrate/frame/balances", default-features = false }
pallet-bridge-messages = { features = ["std", "test-helpers"], path = "../../modules/messages", default-features = false }

[features]
default = ["std"]
std = [
	"bp-header-chain/std",
	"bp-messages/std",
	"bp-parachains/std",
	"bp-polkadot-core/std",
	"bp-relayers/std",
	"bp-runtime/std",
	"bp-xcm-bridge-hub-router/std",
	"bp-xcm-bridge-hub/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-bridge-parachains/std",
	"pallet-bridge-relayers/std",
	"pallet-transaction-payment/std",
	"pallet-utility/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
	"tuplex/std",
	"xcm-builder/std",
	"xcm/std",
	"bp-test-utils/std",
	"pallet-balances/std"
]
runtime-benchmarks = [
	"bp-runtime/test-helpers",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-bridge-grandpa/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"pallet-bridge-messages/test-helpers",
	"pallet-bridge-parachains/runtime-benchmarks",
	"pallet-bridge-relayers/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-trie",
	"xcm-builder/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"bp-header-chain/runtime-benchmarks",
	"bp-messages/runtime-benchmarks",
	"bp-parachains/runtime-benchmarks",
	"bp-polkadot-core/runtime-benchmarks",
	"bp-relayers/runtime-benchmarks",
	"bp-runtime/runtime-benchmarks",
	"bp-test-utils/runtime-benchmarks",
	"bp-xcm-bridge-hub-router/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"sp-trie?/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
integrity-test = ["static_assertions"]
test-helpers = [
	"bp-runtime/test-helpers",
	"sp-trie",
]
try-runtime = [
	"bp-header-chain/try-runtime",
	"bp-messages/try-runtime",
	"bp-parachains/try-runtime",
	"bp-polkadot-core/try-runtime",
	"bp-relayers/try-runtime",
	"bp-runtime/try-runtime",
	"bp-test-utils/try-runtime",
	"bp-xcm-bridge-hub-router/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bridge-grandpa/try-runtime",
	"pallet-bridge-messages/try-runtime",
	"pallet-bridge-parachains/try-runtime",
	"pallet-bridge-relayers/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-utility/try-runtime",
	"sp-runtime/try-runtime",
	"sp-trie?/try-runtime",
	"xcm-builder/try-runtime",
	"sp-io/try-runtime",
	"xcm/try-runtime"
]
