[package]
name = "chain-spec-guide-runtime"
description = "A minimal runtime for chain spec guide (polkadot v1.15.0)"
version = "0.1.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[dependencies]
docify = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
frame = { features = ["experimental", "runtime"], workspace = true }
pallet-balances.workspace = true
pallet-sudo.workspace = true
pallet-timestamp.workspace = true
pallet-transaction-payment.workspace = true
pallet-transaction-payment-rpc-runtime-api.workspace = true
sp-genesis-builder.workspace = true
sp-runtime = { features = ["serde"], workspace = true }
sp-core.workspace = true
sp-keyring.workspace = true
sp-application-crypto = { features = ["serde"], workspace = true }

[build-dependencies]
substrate-wasm-builder = { optional = true, workspace = true, default-features = true }

[dev-dependencies]
chain-spec-builder = { default-features = true, path = "../../../../../substrate/bin/utils/chain-spec-builder", package = "staging-chain-spec-builder" }
sc-chain-spec = { default-features = true, path = "../../../../../substrate/client/chain-spec" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",

	"frame/std",

	"pallet-balances/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",

	"sp-application-crypto/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-keyring/std",
	"sp-runtime/std",

	"serde/std",
	"serde_json/std",
	"substrate-wasm-builder",
	"sc-chain-spec/std",
	"chain-spec-builder/std",
	"substrate-wasm-builder?/std"
]
runtime-benchmarks = [
	"pallet-balances/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"pallet-transaction-payment-rpc-runtime-api/runtime-benchmarks",
	"frame/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sp-genesis-builder/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"chain-spec-builder/runtime-benchmarks",
	"substrate-wasm-builder?/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"pallet-balances/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-transaction-payment-rpc-runtime-api/try-runtime",
	"frame/try-runtime",
	"sc-chain-spec/try-runtime",
	"sp-genesis-builder/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"chain-spec-builder/try-runtime",
	"substrate-wasm-builder?/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime"
]
