[package]
name = "polkadot-primitives-test-helpers"
publish = false
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-primitives-test-helpers (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-application-crypto.workspace = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-core = { features = ["std"], workspace = true, default-features = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
rand = { workspace = true, default-features = true }

[features]
std = [
	"sp-application-crypto/std"
]
runtime-benchmarks = [
	"polkadot-primitives/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"polkadot-primitives/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime"
]
