[package]
name = "rococo-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Rococo emulated chain (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[dependencies]
sp-core.workspace = true
sp-authority-discovery.workspace = true
sp-consensus-babe.workspace = true
sp-consensus-beefy.workspace = true
sp-consensus-beefy.default-features = true
sc-consensus-grandpa.workspace = true
polkadot-primitives.workspace = true
rococo-runtime-constants.workspace = true
rococo-runtime.workspace = true
parachains-common.workspace = true
parachains-common.default-features = true
emulated-integration-tests-common.workspace = true

[features]
std = [
	"emulated-integration-tests-common/std",
	"polkadot-primitives/std",
	"rococo-runtime-constants/std",
	"sc-consensus-grandpa/std",
	"sp-authority-discovery/std",
	"sp-consensus-babe/std",
	"sp-core/std"
]
runtime-benchmarks = [
	"emulated-integration-tests-common/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"rococo-runtime/runtime-benchmarks",
	"rococo-runtime-constants/runtime-benchmarks",
	"sc-consensus-grandpa/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"emulated-integration-tests-common/try-runtime",
	"parachains-common/try-runtime",
	"polkadot-primitives/try-runtime",
	"rococo-runtime/try-runtime",
	"rococo-runtime-constants/try-runtime",
	"sc-consensus-grandpa/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-consensus-beefy/try-runtime",
	"sp-core/try-runtime"
]
