[package]
name = "node-bench"
version = "0.9.0"
authors.workspace = true
description = "Substrate node integration benchmarks. (polkadot v1.15.0)"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-bytes = { workspace = true, default-features = true }
clap = { features = ["derive"], workspace = true }
log = { workspace = true, default-features = true }
node-primitives.workspace = true
node-primitives.default-features = true
node-testing.workspace = true
kitchensink-runtime.workspace = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
derive_more = { features = ["display"], workspace = true }
kvdb = { workspace = true }
kvdb-rocksdb = { workspace = true }
sp-trie.workspace = true
sp-trie.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sc-basic-authorship.workspace = true
sc-basic-authorship.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-timestamp.workspace = true
sp-tracing.workspace = true
sp-tracing.default-features = true
hash-db = { workspace = true, default-features = true }
tempfile = { workspace = true }
fs_extra = { workspace = true }
rand = { features = ["small_rng"], workspace = true, default-features = true }
lazy_static = { workspace = true }
parity-db = { workspace = true }
sc-transaction-pool.workspace = true
sc-transaction-pool.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
futures = { features = ["thread-pool"], workspace = true }

[features]
std = [
	"log/std",
	"node-testing/std",
	"sc-basic-authorship/std",
	"sc-client-api/std",
	"sc-transaction-pool/std",
	"sc-transaction-pool-api/std",
	"sp-consensus/std",
	"sp-timestamp/std"
]
runtime-benchmarks = [
	"kitchensink-runtime/runtime-benchmarks",
	"node-primitives/runtime-benchmarks",
	"node-testing/runtime-benchmarks",
	"sc-basic-authorship/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"kitchensink-runtime/try-runtime",
	"node-primitives/try-runtime",
	"node-testing/try-runtime",
	"sc-basic-authorship/try-runtime",
	"sc-client-api/try-runtime",
	"sc-transaction-pool/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-consensus/try-runtime",
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"sp-timestamp/try-runtime",
	"sp-trie/try-runtime",
	"sp-core/try-runtime"
]
