[package]
name = "mmr-rpc"
version = "37.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Node-specific RPC methods for interaction with Merkle Mountain Range pallet. (polkadot v1.15.0)"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
jsonrpsee = { features = ["client-core", "macros", "server-core"], workspace = true }
serde = { features = ["derive"], workspace = true, default-features = true }
sp-api.workspace = true
sp-api.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-mmr-primitives.workspace = true
sp-mmr-primitives.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[dev-dependencies]
serde_json = { workspace = true, default-features = true }

[features]
std = [
	"sp-blockchain/std"
]
runtime-benchmarks = [
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-mmr-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sp-api/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-mmr-primitives/try-runtime",
	"sp-runtime/try-runtime",
	"sp-core/try-runtime"
]
