[package]
name = "sc-executor"
version = "0.40.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "A crate that provides means of executing/dispatching calls into the runtime. (polkadot v1.15.0)"
documentation = "https://docs.rs/sc-executor"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parking_lot = { workspace = true, default-features = true }
schnellru = { workspace = true }
tracing = { workspace = true, default-features = true }

codec = { workspace = true, default-features = true }
sc-executor-common.workspace = true
sc-executor-common.default-features = true
sc-executor-polkavm.workspace = true
sc-executor-polkavm.default-features = true
sc-executor-wasmtime.workspace = true
sc-executor-wasmtime.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-externalities.workspace = true
sp-externalities.default-features = true
sp-io.workspace = true
sp-io.default-features = true
sp-panic-handler.workspace = true
sp-panic-handler.default-features = true
sp-runtime-interface.workspace = true
sp-runtime-interface.default-features = true
sp-trie.workspace = true
sp-trie.default-features = true
sp-version.workspace = true
sp-version.default-features = true
sp-wasm-interface.workspace = true
sp-wasm-interface.default-features = true

[dev-dependencies]
array-bytes = { workspace = true, default-features = true }
assert_matches = { workspace = true }
wat = { workspace = true }
sc-runtime-test = { path = "runtime-test" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
sp-crypto-hashing = { default-features = true, path = "../../primitives/crypto/hashing" }
sp-state-machine = { default-features = true, path = "../../primitives/state-machine" }
sp-runtime = { default-features = true, path = "../../primitives/runtime" }
sp-maybe-compressed-blob = { default-features = true, path = "../../primitives/maybe-compressed-blob" }
sc-tracing = { default-features = true, path = "../tracing" }
sp-tracing = { default-features = true, path = "../../primitives/tracing" }
tracing-subscriber = { workspace = true }
paste = { workspace = true, default-features = true }
regex = { workspace = true }
criterion = { workspace = true, default-features = true }
env_logger = { workspace = true }
num_cpus = { workspace = true }
tempfile = { workspace = true }

[[bench]]
name = "bench"
harness = false

[features]
default = ["std"]
# This crate does not have `no_std` support, we just require this for tests
std = [
	"sp-api/std",
	"sp-core/std",
	"sp-externalities/std",
	"sp-io/std",
	"sp-runtime-interface/std",
	"sp-trie/std",
	"sp-version/std",
	"sp-wasm-interface/std",
	"sc-executor-common/std",
	"sc-executor-polkavm/std",
	"sc-executor-wasmtime/std",
	"sc-tracing/std",
	"sp-panic-handler/std"
]
wasm-extern-trace = []
runtime-benchmarks = [
	"sc-runtime-test/runtime-benchmarks",
	"sc-tracing/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"substrate-test-runtime/runtime-benchmarks",
	"sc-executor-wasmtime/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-runtime-interface/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sc-executor-common/runtime-benchmarks",
	"sc-executor-polkavm/runtime-benchmarks"
]
try-runtime = [
	"sc-runtime-test/try-runtime",
	"sc-tracing/try-runtime",
	"sp-api/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"sp-trie/try-runtime",
	"sp-version/try-runtime",
	"substrate-test-runtime/try-runtime",
	"sc-executor-wasmtime/try-runtime",
	"sp-io/try-runtime",
	"sp-runtime-interface/try-runtime",
	"sp-core/try-runtime",
	"sc-executor-common/try-runtime",
	"sc-executor-polkavm/try-runtime"
]
