[package]
name = "polkadot-primitives"
version = "15.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared primitives used by Polkadot runtime (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
bitvec = { features = ["alloc", "serde"], workspace = true }
hex-literal = { workspace = true, default-features = true }
codec = { features = ["bit-vec", "derive"], workspace = true }
scale-info = { features = ["bit-vec", "derive", "serde"], workspace = true }
log = { workspace = true }
serde = { features = ["alloc", "derive"], workspace = true }
sp-application-crypto = { features = ["serde"], workspace = true }
sp-inherents.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-api.workspace = true
sp-arithmetic = { features = ["serde"], workspace = true }
sp-authority-discovery = { features = ["serde"], workspace = true }
sp-consensus-slots = { features = ["serde"], workspace = true }
sp-io.workspace = true
sp-keystore = { optional = true, workspace = true }
sp-staking = { features = ["serde"], workspace = true }
polkadot-core-primitives.workspace = true
polkadot-parachain-primitives.workspace = true

[features]
default = ["std"]
std = [
	"bitvec/std",
	"codec/std",
	"log/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain-primitives/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-arithmetic/std",
	"sp-authority-discovery/std",
	"sp-consensus-slots/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-keystore",
	"sp-keystore?/std",
	"sp-runtime/std",
	"sp-staking/std",
]
runtime-benchmarks = [
	"polkadot-parachain-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"polkadot-core-primitives/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore?/runtime-benchmarks"
]
try-runtime = [
	"polkadot-core-primitives/try-runtime",
	"polkadot-parachain-primitives/try-runtime",
	"sp-api/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-staking/try-runtime",
	"sp-consensus-slots/try-runtime",
	"sp-io/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore?/try-runtime"
]
