[package]
name = "polkadot-node-subsystem-test-helpers"
description = "Subsystem traits and message definitions (polkadot v1.15.0)"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true, default-features = true }
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-erasure-coding.workspace = true
polkadot-erasure-coding.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-utils.workspace = true
sc-utils.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sc-keystore.workspace = true
sc-keystore.default-features = true
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-application-crypto.workspace = true
sp-application-crypto.default-features = true

[features]
std = [
	"polkadot-erasure-coding/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-util/std",
	"sc-client-api/std",
	"sc-keystore/std",
	"sc-utils/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-erasure-coding/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sc-keystore/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-erasure-coding/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-primitives/try-runtime",
	"sc-client-api/try-runtime",
	"sp-keyring/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime",
	"sc-keystore/try-runtime",
	"sp-keystore/try-runtime"
]
