[package]
name = "cumulus-client-consensus-relay-chain"
description = "The relay-chain provided consensus algorithm (polkadot v1.15.0)"
version = "0.17.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true, default-features = true }
tracing = { workspace = true, default-features = true }
sc-consensus.workspace = true
sc-consensus.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
cumulus-client-consensus-common.workspace = true
cumulus-client-consensus-common.default-features = true
cumulus-primitives-core.workspace = true
cumulus-primitives-core.default-features = true
cumulus-relay-chain-interface.workspace = true
cumulus-relay-chain-interface.default-features = true

[features]
std = [
	"cumulus-client-consensus-common/std",
	"cumulus-relay-chain-interface/std",
	"sc-consensus/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"prometheus-endpoint/std"
]
runtime-benchmarks = [
	"cumulus-client-consensus-common/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-relay-chain-interface/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"cumulus-client-consensus-common/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"sc-consensus/try-runtime",
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"cumulus-relay-chain-interface/try-runtime",
	"sp-core/try-runtime"
]
