[package]
description = "Substrate mixnet types and runtime interface (polkadot v1.15.0)"
name = "sp-mixnet"
version = "0.12.0"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition.workspace = true
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
sp-api.workspace = true
sp-application-crypto.workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-application-crypto/std",
]
runtime-benchmarks = [
	"sp-api/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks"
]
try-runtime = [
	"sp-api/try-runtime",
	"sp-application-crypto/try-runtime"
]
