[package]
name = "sc-rpc-spec-v2"
version = "0.44.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate RPC interface v2. (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { features = ["client-core", "macros", "server-core"], workspace = true }
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-rpc.workspace = true
sp-rpc.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-version.workspace = true
sp-version.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-utils.workspace = true
sc-utils.default-features = true
sc-rpc.workspace = true
sc-rpc.default-features = true
codec = { workspace = true, default-features = true }
thiserror = { workspace = true }
serde = { workspace = true, default-features = true }
hex = { workspace = true, default-features = true }
futures = { workspace = true }
parking_lot = { workspace = true, default-features = true }
tokio-stream = { features = ["sync"], workspace = true }
tokio = { features = ["sync"], workspace = true, default-features = true }
array-bytes = { workspace = true, default-features = true }
log = { workspace = true, default-features = true }
futures-util = { workspace = true }
rand = { workspace = true, default-features = true }
schnellru = { workspace = true }

[dev-dependencies]
jsonrpsee = { features = ["server", "ws-client"], workspace = true }
serde_json = { workspace = true, default-features = true }
tokio = { features = ["macros"], workspace = true, default-features = true }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
substrate-test-runtime-transaction-pool = { path = "../../test-utils/runtime/transaction-pool" }
sp-consensus = { default-features = true, path = "../../primitives/consensus/common" }
sp-externalities = { default-features = true, path = "../../primitives/externalities" }
sp-maybe-compressed-blob = { default-features = true, path = "../../primitives/maybe-compressed-blob" }
sc-block-builder = { default-features = true, path = "../block-builder" }
sc-service = { features = ["test-helpers"], default-features = true, path = "../service" }
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }
sc-transaction-pool = { default-features = true, path = "../transaction-pool" }

[features]
std = [
	"futures-util/std",
	"log/std",
	"sc-block-builder/std",
	"sc-chain-spec/std",
	"sc-client-api/std",
	"sc-rpc/std",
	"sc-service/std",
	"sc-transaction-pool/std",
	"sc-transaction-pool-api/std",
	"sc-utils/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"sp-rpc/std",
	"substrate-test-runtime-client/std",
	"substrate-test-runtime-transaction-pool/std"
]
runtime-benchmarks = [
	"sc-block-builder/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-rpc/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"substrate-test-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"substrate-test-runtime-transaction-pool/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-rpc/runtime-benchmarks"
]
try-runtime = [
	"sc-block-builder/try-runtime",
	"sc-chain-spec/try-runtime",
	"sc-client-api/try-runtime",
	"sc-rpc/try-runtime",
	"sc-service/try-runtime",
	"sc-transaction-pool/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-runtime/try-runtime",
	"sp-version/try-runtime",
	"substrate-test-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"substrate-test-runtime-transaction-pool/try-runtime",
	"sp-core/try-runtime",
	"sp-rpc/try-runtime"
]
