[package]
name = "sc-rpc"
version = "39.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate Client RPC (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
futures = { workspace = true }
jsonrpsee = { features = ["server"], workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
sc-block-builder.workspace = true
sc-block-builder.default-features = true
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-mixnet.workspace = true
sc-mixnet.default-features = true
sc-rpc-api.workspace = true
sc-rpc-api.default-features = true
sc-tracing.workspace = true
sc-tracing.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sc-utils.workspace = true
sc-utils.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-offchain.workspace = true
sp-offchain.default-features = true
sp-rpc.workspace = true
sp-rpc.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-session.workspace = true
sp-session.default-features = true
sp-version.workspace = true
sp-version.default-features = true
sp-statement-store.workspace = true
sp-statement-store.default-features = true
tokio = { workspace = true, default-features = true }

[dev-dependencies]
env_logger = { workspace = true }
assert_matches = { workspace = true }
sc-block-builder = { default-features = true, path = "../block-builder" }
sc-network = { default-features = true, path = "../network" }
sc-network-common = { default-features = true, path = "../network/common" }
sc-transaction-pool = { default-features = true, path = "../transaction-pool" }
sp-consensus = { default-features = true, path = "../../primitives/consensus/common" }
sp-crypto-hashing = { default-features = true, path = "../../primitives/crypto/hashing" }
tokio = { workspace = true, default-features = true }
sp-io = { default-features = true, path = "../../primitives/io" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
pretty_assertions = { workspace = true }
tracing-subscriber = { features = ["env-filter"], workspace = true }

[features]
test-helpers = []
std = [
	"log/std",
	"sc-block-builder/std",
	"sc-chain-spec/std",
	"sc-client-api/std",
	"sc-mixnet/std",
	"sc-network/std",
	"sc-network-common/std",
	"sc-rpc-api/std",
	"sc-tracing/std",
	"sc-transaction-pool/std",
	"sc-transaction-pool-api/std",
	"sc-utils/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"sp-rpc/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-block-builder/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-mixnet/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-network-common/runtime-benchmarks",
	"sc-rpc-api/runtime-benchmarks",
	"sc-tracing/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-offchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-session/runtime-benchmarks",
	"sp-statement-store/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks",
	"sp-rpc/runtime-benchmarks"
]
try-runtime = [
	"sc-block-builder/try-runtime",
	"sc-chain-spec/try-runtime",
	"sc-client-api/try-runtime",
	"sc-mixnet/try-runtime",
	"sc-network/try-runtime",
	"sc-network-common/try-runtime",
	"sc-rpc-api/try-runtime",
	"sc-tracing/try-runtime",
	"sc-transaction-pool/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-offchain/try-runtime",
	"sp-runtime/try-runtime",
	"sp-session/try-runtime",
	"sp-statement-store/try-runtime",
	"sp-version/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime",
	"sp-rpc/try-runtime"
]
