[package]
name = "polkadot-statement-distribution"
description = "Statement Distribution Subsystem (polkadot v1.15.0)"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }
gum.workspace = true
gum.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
sp-staking.workspace = true
sp-keystore.workspace = true
sp-keystore.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-node-network-protocol.workspace = true
polkadot-node-network-protocol.default-features = true
arrayvec = { workspace = true }
indexmap = { workspace = true }
codec = { features = ["derive"], workspace = true }
thiserror = { workspace = true }
fatality = { workspace = true }
bitvec = { workspace = true, default-features = true }

[dev-dependencies]
async-channel = { workspace = true }
assert_matches = { workspace = true }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-authority-discovery = { default-features = true, path = "../../../../substrate/primitives/authority-discovery" }
sp-keyring = { default-features = true, path = "../../../../substrate/primitives/keyring" }
sp-core = { default-features = true, path = "../../../../substrate/primitives/core" }
sp-application-crypto = { default-features = true, path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { default-features = true, path = "../../../../substrate/primitives/keystore" }
sp-tracing = { default-features = true, path = "../../../../substrate/primitives/tracing" }
sc-keystore = { default-features = true, path = "../../../../substrate/client/keystore" }
sc-network = { default-features = true, path = "../../../../substrate/client/network" }
futures-timer = { workspace = true }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
rand_chacha = { workspace = true, default-features = true }
polkadot-subsystem-bench = { path = "../../subsystem-bench" }

[[bench]]
name = "statement-distribution-regression-bench"
path = "benches/statement-distribution-regression-bench.rs"
harness = false
required-features = ["subsystem-benchmarks"]

[features]
subsystem-benchmarks = []
std = [
	"codec/std",
	"polkadot-node-network-protocol/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-primitives-test-helpers/std",
	"polkadot-subsystem-bench/std",
	"sc-keystore/std",
	"sc-network/std",
	"sp-staking/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"polkadot-subsystem-bench/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sc-keystore/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-network-protocol/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"polkadot-subsystem-bench/try-runtime",
	"sc-network/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-keyring/try-runtime",
	"sp-staking/try-runtime",
	"gum/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime",
	"sc-keystore/try-runtime",
	"sp-keystore/try-runtime"
]
