[package]
name = "frame-omni-bencher"
version = "0.6.0"
description = "Freestanding benchmark runner for any Polkadot runtime. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap = { features = ["derive"], workspace = true }
cumulus-primitives-proof-size-hostfunction.workspace = true
cumulus-primitives-proof-size-hostfunction.default-features = true
frame-benchmarking-cli.workspace = true
sc-cli.workspace = true
sc-cli.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-statement-store.workspace = true
sp-statement-store.default-features = true
env_logger = { workspace = true }
log = { workspace = true }

[features]
std = [
	"frame-benchmarking-cli/std",
	"log/std",
	"sc-cli/std"
]
runtime-benchmarks = [
	"frame-benchmarking-cli/runtime-benchmarks",
	"sc-cli/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-statement-store/runtime-benchmarks",
	"cumulus-primitives-proof-size-hostfunction/runtime-benchmarks"
]
try-runtime = [
	"frame-benchmarking-cli/try-runtime",
	"sc-cli/try-runtime",
	"sp-runtime/try-runtime",
	"sp-statement-store/try-runtime",
	"cumulus-primitives-proof-size-hostfunction/try-runtime"
]
