[package]
name = "polkadot-dispute-distribution"
version = "17.0.1"
description = "Polkadot Dispute Distribution subsystem, which ensures all concerned validators are aware of a dispute and have the relevant votes. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }
gum.workspace = true
gum.default-features = true
derive_more = { workspace = true, default-features = true }
codec = { features = ["std"], workspace = true, default-features = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-erasure-coding.workspace = true
polkadot-erasure-coding.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-network-protocol.workspace = true
polkadot-node-network-protocol.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sp-application-crypto.workspace = true
sp-application-crypto.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
thiserror = { workspace = true }
fatality = { workspace = true }
schnellru = { workspace = true }
indexmap = { workspace = true }

[dev-dependencies]
async-channel = { workspace = true }
async-trait = { workspace = true }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { default-features = true, path = "../../../../substrate/primitives/keyring" }
sp-tracing = { default-features = true, path = "../../../../substrate/primitives/tracing" }
sc-keystore = { default-features = true, path = "../../../../substrate/client/keystore" }
futures-timer = { workspace = true }
assert_matches = { workspace = true }
lazy_static = { workspace = true }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }

[features]
std = [
	"polkadot-erasure-coding/std",
	"polkadot-node-network-protocol/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-primitives-test-helpers/std",
	"sc-keystore/std",
	"sc-network/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-erasure-coding/runtime-benchmarks",
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sc-keystore/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-erasure-coding/try-runtime",
	"polkadot-node-network-protocol/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"sc-network/try-runtime",
	"sp-keyring/try-runtime",
	"gum/try-runtime",
	"sp-application-crypto/try-runtime",
	"sc-keystore/try-runtime",
	"sp-keystore/try-runtime"
]
