[package]
name = "cumulus-primitives-core"
version = "0.15.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Cumulus related core primitive types and traits (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
sp-api.workspace = true
sp-runtime.workspace = true
sp-trie.workspace = true
polkadot-core-primitives.workspace = true
polkadot-parachain-primitives.workspace = true
polkadot-primitives.workspace = true
xcm.workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain-primitives/std",
	"polkadot-primitives/std",
	"scale-info/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-trie/std",
	"xcm/std",
]
runtime-benchmarks = [
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"polkadot-core-primitives/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"polkadot-core-primitives/try-runtime",
	"polkadot-parachain-primitives/try-runtime",
	"polkadot-primitives/try-runtime",
	"sp-api/try-runtime",
	"sp-runtime/try-runtime",
	"sp-trie/try-runtime",
	"xcm/try-runtime"
]
