[package]
name = "polkadot-node-core-approval-voting"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Approval Voting Subsystem of the Polkadot node (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }
codec = { features = ["bit-vec", "derive"], workspace = true }
gum.workspace = true
gum.default-features = true
bitvec = { features = ["alloc"], workspace = true }
schnellru = { workspace = true }
merlin = { workspace = true, default-features = true }
schnorrkel = { workspace = true, default-features = true }
kvdb = { workspace = true }
derive_more = { workspace = true, default-features = true }
thiserror = { workspace = true }
itertools = { workspace = true }
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-overseer.workspace = true
polkadot-overseer.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-jaeger.workspace = true
polkadot-node-jaeger.default-features = true
sc-keystore.workspace = true
sp-consensus.workspace = true
sp-consensus-slots.workspace = true
sp-application-crypto = { features = ["full_crypto"], workspace = true }
sp-runtime.workspace = true
# rand_core should match schnorrkel
rand_core = { workspace = true }
rand_chacha = { workspace = true, default-features = true }
rand = { workspace = true, default-features = true }

[dev-dependencies]
async-trait = { workspace = true }
parking_lot = { workspace = true, default-features = true }
sp-keyring = { default-features = true, path = "../../../../substrate/primitives/keyring" }
sp-keystore = { default-features = true, path = "../../../../substrate/primitives/keystore" }
sp-core = { default-features = true, path = "../../../../substrate/primitives/core" }
sp-consensus-babe = { default-features = true, path = "../../../../substrate/primitives/consensus/babe" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = { workspace = true }
kvdb-memorydb = { workspace = true }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
log = { workspace = true, default-features = true }
env_logger = { workspace = true }

polkadot-subsystem-bench = { path = "../../subsystem-bench" }

[[bench]]
name = "approval-voting-regression-bench"
path = "benches/approval-voting-regression-bench.rs"
harness = false
required-features = ["subsystem-benchmarks"]

[features]
subsystem-benchmarks = []
std = [
	"bitvec/std",
	"log/std",
	"codec/std",
	"polkadot-node-jaeger/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-overseer/std",
	"polkadot-primitives-test-helpers/std",
	"polkadot-subsystem-bench/std",
	"rand_core/std",
	"sc-keystore/std",
	"sp-application-crypto/std",
	"sp-consensus/std",
	"sp-consensus-slots/std",
	"sp-runtime/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-jaeger/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-overseer/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"polkadot-subsystem-bench/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sc-keystore/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-primitives/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"polkadot-subsystem-bench/try-runtime",
	"sp-consensus/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"polkadot-node-jaeger/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-overseer/try-runtime",
	"sp-consensus-slots/try-runtime",
	"gum/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime",
	"sc-keystore/try-runtime",
	"sp-keystore/try-runtime"
]
