[package]
name = "sp-blockchain"
version = "37.0.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate blockchain traits and primitives. (polkadot v1.15.0)"
documentation = "https://docs.rs/sp-blockchain"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true, default-features = true }
schnellru = { workspace = true }
thiserror = { workspace = true }
sp-api.workspace = true
sp-api.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-database.workspace = true
sp-database.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
tracing = { workspace = true, default-features = true }

[features]
std = [
	"codec/std",
	"sp-consensus/std"
]
runtime-benchmarks = [
	"sp-api/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sp-api/try-runtime",
	"sp-consensus/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"sp-core/try-runtime"
]
