[package]
name = "polkadot-node-core-chain-api"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "The Chain API subsystem provides access to chain related utility functions like block number to hash conversions. (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gum.workspace = true
gum.default-features = true
polkadot-node-metrics.workspace = true
polkadot-node-metrics.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-types.workspace = true
polkadot-node-subsystem-types.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus-babe.workspace = true
sc-consensus-babe.default-features = true

[dev-dependencies]
futures = { features = ["thread-pool"], workspace = true }
maplit = { workspace = true }
codec = { workspace = true, default-features = true }
polkadot-node-primitives = { default-features = true, path = "../../primitives" }
polkadot-primitives = { default-features = true, path = "../../../primitives" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { default-features = true, path = "../../../../substrate/primitives/core" }
sp-blockchain = { default-features = true, path = "../../../../substrate/primitives/blockchain" }

[features]
std = [
	"polkadot-node-metrics/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-types/std",
	"sc-client-api/std",
	"sc-consensus-babe/std",
	"sp-blockchain/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-metrics/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-types/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus-babe/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-metrics/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-types/try-runtime",
	"polkadot-primitives/try-runtime",
	"sc-client-api/try-runtime",
	"sc-consensus-babe/try-runtime",
	"sp-blockchain/try-runtime",
	"gum/try-runtime",
	"sp-core/try-runtime"
]
