[package]
name = "node-rpc"
version = "3.0.0"
authors.workspace = true
description = "Substrate node rpc methods. (polkadot v1.15.0)"
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { features = ["server"], workspace = true }
node-primitives.workspace = true
node-primitives.default-features = true
pallet-transaction-payment-rpc.workspace = true
pallet-transaction-payment-rpc.default-features = true
mmr-rpc.workspace = true
mmr-rpc.default-features = true
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus-babe.workspace = true
sc-consensus-babe.default-features = true
sc-consensus-babe-rpc.workspace = true
sc-consensus-babe-rpc.default-features = true
sc-consensus-beefy.workspace = true
sc-consensus-beefy.default-features = true
sc-consensus-beefy-rpc.workspace = true
sc-consensus-beefy-rpc.default-features = true
sp-consensus-beefy.workspace = true
sp-consensus-beefy.default-features = true
sc-consensus-grandpa.workspace = true
sc-consensus-grandpa.default-features = true
sc-consensus-grandpa-rpc.workspace = true
sc-consensus-grandpa-rpc.default-features = true
sc-mixnet.workspace = true
sc-mixnet.default-features = true
sc-rpc.workspace = true
sc-rpc.default-features = true
sc-rpc-api.workspace = true
sc-rpc-api.default-features = true
sc-rpc-spec-v2.workspace = true
sc-rpc-spec-v2.default-features = true
sc-sync-state-rpc.workspace = true
sc-sync-state-rpc.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-consensus-babe.workspace = true
sp-consensus-babe.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-application-crypto.workspace = true
sp-application-crypto.default-features = true
sp-statement-store.workspace = true
sp-statement-store.default-features = true
substrate-frame-rpc-system.workspace = true
substrate-frame-rpc-system.default-features = true
substrate-state-trie-migration-rpc.workspace = true
substrate-state-trie-migration-rpc.default-features = true

[features]
std = [
	"mmr-rpc/std",
	"pallet-transaction-payment-rpc/std",
	"sc-chain-spec/std",
	"sc-client-api/std",
	"sc-consensus-babe/std",
	"sc-consensus-babe-rpc/std",
	"sc-consensus-beefy/std",
	"sc-consensus-beefy-rpc/std",
	"sc-consensus-grandpa/std",
	"sc-consensus-grandpa-rpc/std",
	"sc-mixnet/std",
	"sc-rpc/std",
	"sc-rpc-api/std",
	"sc-rpc-spec-v2/std",
	"sc-sync-state-rpc/std",
	"sc-transaction-pool-api/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"substrate-frame-rpc-system/std",
	"substrate-state-trie-migration-rpc/std"
]
runtime-benchmarks = [
	"mmr-rpc/runtime-benchmarks",
	"node-primitives/runtime-benchmarks",
	"pallet-transaction-payment-rpc/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus-babe/runtime-benchmarks",
	"sc-consensus-babe-rpc/runtime-benchmarks",
	"sc-consensus-beefy/runtime-benchmarks",
	"sc-consensus-beefy-rpc/runtime-benchmarks",
	"sc-consensus-grandpa/runtime-benchmarks",
	"sc-consensus-grandpa-rpc/runtime-benchmarks",
	"sc-mixnet/runtime-benchmarks",
	"sc-rpc/runtime-benchmarks",
	"sc-rpc-api/runtime-benchmarks",
	"sc-rpc-spec-v2/runtime-benchmarks",
	"sc-sync-state-rpc/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-statement-store/runtime-benchmarks",
	"substrate-frame-rpc-system/runtime-benchmarks",
	"substrate-state-trie-migration-rpc/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"mmr-rpc/try-runtime",
	"node-primitives/try-runtime",
	"pallet-transaction-payment-rpc/try-runtime",
	"sc-chain-spec/try-runtime",
	"sc-client-api/try-runtime",
	"sc-consensus-babe/try-runtime",
	"sc-consensus-babe-rpc/try-runtime",
	"sc-consensus-beefy/try-runtime",
	"sc-consensus-beefy-rpc/try-runtime",
	"sc-consensus-grandpa/try-runtime",
	"sc-consensus-grandpa-rpc/try-runtime",
	"sc-mixnet/try-runtime",
	"sc-rpc/try-runtime",
	"sc-rpc-api/try-runtime",
	"sc-rpc-spec-v2/try-runtime",
	"sc-sync-state-rpc/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-consensus-beefy/try-runtime",
	"sp-runtime/try-runtime",
	"sp-statement-store/try-runtime",
	"substrate-frame-rpc-system/try-runtime",
	"substrate-state-trie-migration-rpc/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-keystore/try-runtime"
]
