[package]
description = "Substrate offchain workers (polkadot v1.15.0)"
name = "sc-offchain"
version = "39.0.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { workspace = true, default-features = true }
bytes = { workspace = true, default-features = true }
codec = { features = ["derive"], workspace = true, default-features = true }
fnv = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
hyperv14 = { features = ["http2", "stream"], workspace = true, default-features = true }
hyper-rustls = { features = ["http2"], workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true, default-features = true }
rand = { workspace = true, default-features = true }
threadpool = { workspace = true }
tracing = { workspace = true, default-features = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sc-network-common.workspace = true
sc-network-common.default-features = true
sc-network-types.workspace = true
sc-network-types.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sc-utils.workspace = true
sc-utils.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-offchain.workspace = true
sp-offchain.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-externalities.workspace = true
sp-externalities.default-features = true
log = { workspace = true, default-features = true }

[dev-dependencies]
async-trait = { workspace = true }
lazy_static = { workspace = true }
tokio = { workspace = true, default-features = true }
sc-block-builder = { default-features = true, path = "../block-builder" }
sc-client-db = { default-features = true, path = "../db" }
sc-transaction-pool = { default-features = true, path = "../transaction-pool" }
sc-transaction-pool-api = { default-features = true, path = "../transaction-pool/api" }
sp-consensus = { default-features = true, path = "../../primitives/consensus/common" }
sp-tracing = { default-features = true, path = "../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }

[features]
default = []
std = [
	"log/std",
	"sc-block-builder/std",
	"sc-client-api/std",
	"sc-client-db/std",
	"sc-network/std",
	"sc-network-common/std",
	"sc-network-types/std",
	"sc-transaction-pool/std",
	"sc-transaction-pool-api/std",
	"sc-utils/std",
	"sp-consensus/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-block-builder/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-network-common/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-offchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"sc-block-builder/try-runtime",
	"sc-client-api/try-runtime",
	"sc-client-db/try-runtime",
	"sc-network/try-runtime",
	"sc-network-common/try-runtime",
	"sc-transaction-pool/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-consensus/try-runtime",
	"sp-offchain/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
