[package]
name = "asset-hub-rococo-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Asset Hub Rococo emulated chain (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[dependencies]
sp-core.workspace = true
frame-support.workspace = true
parachains-common.workspace = true
parachains-common.default-features = true
cumulus-primitives-core.workspace = true
emulated-integration-tests-common.workspace = true
asset-hub-rococo-runtime.workspace = true
asset-hub-rococo-runtime.default-features = true
rococo-emulated-chain.workspace = true
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }
xcm.workspace = true

[features]
std = [
	"cumulus-primitives-core/std",
	"emulated-integration-tests-common/std",
	"frame-support/std",
	"rococo-emulated-chain/std",
	"sp-core/std",
	"xcm/std"
]
runtime-benchmarks = [
	"asset-hub-rococo-runtime/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"emulated-integration-tests-common/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"rococo-emulated-chain/runtime-benchmarks",
	"testnet-parachains-constants/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"asset-hub-rococo-runtime/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"emulated-integration-tests-common/try-runtime",
	"frame-support/try-runtime",
	"parachains-common/try-runtime",
	"rococo-emulated-chain/try-runtime",
	"testnet-parachains-constants/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
