[package]
name = "sc-block-builder"
version = "0.42.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate block builder (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true, default-features = true }
sp-api.workspace = true
sp-api.default-features = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-trie.workspace = true
sp-trie.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[dev-dependencies]
sp-state-machine = { default-features = true, path = "../../primitives/state-machine" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }

[features]
std = [
	"sp-blockchain/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"sp-trie/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sp-core/try-runtime"
]
