[package]
name = "polkadot-node-core-provisioner"
version = "17.0.0"
description = "Responsible for assembling a relay chain block from a set of available parachain candidates (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bitvec = { features = ["alloc"], workspace = true }
futures = { workspace = true }
gum.workspace = true
gum.default-features = true
thiserror = { workspace = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
futures-timer = { workspace = true }
fatality = { workspace = true }
schnellru = { workspace = true }

[dev-dependencies]
sp-application-crypto = { default-features = true, path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { default-features = true, path = "../../../../substrate/primitives/keystore" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
rstest = { workspace = true }

[features]
std = [
	"bitvec/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-primitives-test-helpers/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"gum/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-keystore/try-runtime"
]
