[package]
name = "generate-bags"
version = "37.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Bag threshold generation script for pallet-bag-list (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
frame-support.workspace = true
frame-support.default-features = true
frame-election-provider-support.workspace = true
frame-election-provider-support.default-features = true
frame-system.workspace = true
frame-system.default-features = true
pallet-staking.workspace = true
pallet-staking.default-features = true
sp-staking.workspace = true
sp-staking.default-features = true

# third party
chrono = { workspace = true }
num-format = { workspace = true }

[features]
std = []
runtime-benchmarks = [
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"sp-staking/runtime-benchmarks"
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-staking/try-runtime",
	"sp-staking/try-runtime"
]
