[package]
name = "bridge-hub-test-utils"
version = "0.17.0"
authors.workspace = true
edition.workspace = true
description = "Utils for BridgeHub testing (polkadot v1.15.0)"
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive", "max-encoded-len"], workspace = true }
impl-trait-for-tuples = { workspace = true }
log = { workspace = true }
frame-support.workspace = true
frame-system.workspace = true
sp-core.workspace = true
sp-io.workspace = true
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-runtime.workspace = true
sp-tracing.workspace = true
sp-tracing.default-features = true
pallet-balances.workspace = true
pallet-utility.workspace = true
pallet-timestamp.workspace = true
asset-test-utils.workspace = true
asset-test-utils.default-features = true
cumulus-pallet-parachain-system.workspace = true
cumulus-pallet-xcmp-queue.workspace = true
parachains-common.workspace = true
parachains-runtimes-test-utils.workspace = true
xcm.workspace = true
xcm-builder.workspace = true
xcm-executor.workspace = true
bp-header-chain.workspace = true
bp-messages.workspace = true
bp-polkadot-core.workspace = true
bp-relayers.workspace = true
bp-runtime.workspace = true
bp-test-utils.workspace = true
pallet-bridge-grandpa.workspace = true
pallet-bridge-parachains.workspace = true
pallet-bridge-messages = { features = ["test-helpers"], workspace = true }
pallet-bridge-relayers.workspace = true
bridge-runtime-common.workspace = true

[features]
default = ["std"]
std = [
	"asset-test-utils/std",
	"bp-header-chain/std",
	"bp-messages/std",
	"bp-polkadot-core/std",
	"bp-relayers/std",
	"bp-runtime/std",
	"bp-test-utils/std",
	"bridge-runtime-common/std",
	"codec/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcmp-queue/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-balances/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-bridge-parachains/std",
	"pallet-bridge-relayers/std",
	"pallet-timestamp/std",
	"pallet-utility/std",
	"parachains-common/std",
	"parachains-runtimes-test-utils/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]
runtime-benchmarks = [
	"asset-test-utils/runtime-benchmarks",
	"bp-header-chain/runtime-benchmarks",
	"bp-messages/runtime-benchmarks",
	"bp-polkadot-core/runtime-benchmarks",
	"bp-relayers/runtime-benchmarks",
	"bp-runtime/runtime-benchmarks",
	"bp-test-utils/runtime-benchmarks",
	"bridge-runtime-common/runtime-benchmarks",
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bridge-grandpa/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"pallet-bridge-parachains/runtime-benchmarks",
	"pallet-bridge-relayers/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"parachains-runtimes-test-utils/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"asset-test-utils/try-runtime",
	"bp-header-chain/try-runtime",
	"bp-messages/try-runtime",
	"bp-polkadot-core/try-runtime",
	"bp-relayers/try-runtime",
	"bp-runtime/try-runtime",
	"bp-test-utils/try-runtime",
	"bridge-runtime-common/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bridge-grandpa/try-runtime",
	"pallet-bridge-messages/try-runtime",
	"pallet-bridge-parachains/try-runtime",
	"pallet-bridge-relayers/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-utility/try-runtime",
	"parachains-common/try-runtime",
	"parachains-runtimes-test-utils/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"xcm-builder/try-runtime",
	"xcm-executor/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
