[package]
name = "cumulus-primitives-storage-weight-reclaim"
version = "7.0.1"
authors.workspace = true
edition.workspace = true
description = "Utilities to reclaim storage weight. (polkadot v1.15.0)"
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame-support.workspace = true
frame-system.workspace = true
sp-runtime.workspace = true
cumulus-primitives-core.workspace = true
cumulus-primitives-proof-size-hostfunction.workspace = true
docify = { workspace = true }

[dev-dependencies]
sp-trie = { path = "../../../substrate/primitives/trie", default-features = false }
sp-io = { path = "../../../substrate/primitives/io", default-features = false }
cumulus-test-runtime = { path = "../../test/runtime" }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-proof-size-hostfunction/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-trie/std"
]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-test-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"cumulus-primitives-proof-size-hostfunction/runtime-benchmarks",
	"sp-io/runtime-benchmarks"
]
try-runtime = [
	"cumulus-primitives-core/try-runtime",
	"cumulus-test-runtime/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
	"sp-trie/try-runtime",
	"cumulus-primitives-proof-size-hostfunction/try-runtime",
	"sp-io/try-runtime"
]
