[package]
name = "sp-consensus-pow"
version = "0.40.0"
authors.workspace = true
description = "Primitives for Aura consensus (polkadot v1.15.0)"
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
sp-api.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
]
runtime-benchmarks = [
	"sp-api/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sp-api/try-runtime",
	"sp-runtime/try-runtime",
	"sp-core/try-runtime"
]
