[package]
name = "cumulus-client-consensus-common"
description = "Cumulus specific common consensus implementations (polkadot v1.15.0)"
version = "0.17.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
codec = { features = ["derive"], workspace = true, default-features = true }
dyn-clone = { workspace = true }
futures = { workspace = true }
log = { workspace = true, default-features = true }
tracing = { workspace = true, default-features = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus.workspace = true
sc-consensus.default-features = true
sc-consensus-babe.workspace = true
sc-consensus-babe.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-consensus-slots.workspace = true
sp-consensus-slots.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-timestamp.workspace = true
sp-timestamp.default-features = true
sp-trie.workspace = true
sp-trie.default-features = true
sp-version.workspace = true
sp-version.default-features = true
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
cumulus-primitives-core.workspace = true
cumulus-primitives-core.default-features = true
cumulus-relay-chain-interface.workspace = true
cumulus-relay-chain-interface.default-features = true
cumulus-client-pov-recovery.workspace = true
cumulus-client-pov-recovery.default-features = true
schnellru = { workspace = true }

[dev-dependencies]
futures-timer = { workspace = true }

# Substrate
sp-tracing = { default-features = true, path = "../../../../substrate/primitives/tracing" }

# Cumulus
cumulus-test-client = { path = "../../../test/client" }
cumulus-test-relay-sproof-builder = { default-features = true, path = "../../../test/relay-sproof-builder" }

[features]
std = [
	"cumulus-client-pov-recovery/std",
	"cumulus-relay-chain-interface/std",
	"cumulus-test-client/std",
	"log/std",
	"sc-client-api/std",
	"sc-consensus/std",
	"sc-consensus-babe/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"prometheus-endpoint/std"
]
runtime-benchmarks = [
	"cumulus-client-pov-recovery/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-relay-chain-interface/runtime-benchmarks",
	"cumulus-test-client/runtime-benchmarks",
	"cumulus-test-relay-sproof-builder/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-consensus-babe/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"cumulus-client-pov-recovery/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"cumulus-test-client/try-runtime",
	"cumulus-test-relay-sproof-builder/try-runtime",
	"polkadot-primitives/try-runtime",
	"sc-client-api/try-runtime",
	"sc-consensus/try-runtime",
	"sc-consensus-babe/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-runtime/try-runtime",
	"sp-timestamp/try-runtime",
	"sp-trie/try-runtime",
	"sp-version/try-runtime",
	"cumulus-relay-chain-interface/try-runtime",
	"sp-consensus-slots/try-runtime",
	"sp-core/try-runtime"
]
