[package]
name = "pallet-beefy"
version = "38.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "BEEFY FRAME pallet (polkadot v1.15.0)"
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
log = { workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
serde = { optional = true, workspace = true, default-features = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-authorship.workspace = true
pallet-session.workspace = true
sp-consensus-beefy = { features = ["serde"], workspace = true }
sp-runtime = { features = ["serde"], workspace = true }
sp-session.workspace = true
sp-staking = { features = ["serde"], workspace = true }

[dev-dependencies]
frame-election-provider-support = { default-features = true, path = "../election-provider-support" }
pallet-balances = { default-features = true, path = "../balances" }
pallet-offences = { default-features = true, path = "../offences" }
pallet-staking = { default-features = true, path = "../staking" }
pallet-staking-reward-curve = { default-features = true, path = "../staking/reward-curve" }
pallet-timestamp = { default-features = true, path = "../timestamp" }
sp-core = { default-features = true, path = "../../primitives/core" }
sp-io = { default-features = true, path = "../../primitives/io" }
sp-staking = { default-features = true, path = "../../primitives/staking" }
sp-state-machine = { path = "../../primitives/state-machine", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-session/std",
	"scale-info/std",
	"serde/std",
	"sp-consensus-beefy/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-state-machine/std",
	"pallet-staking-reward-curve/std"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-session/try-runtime",
	"sp-runtime/try-runtime",
	"frame-election-provider-support/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-staking-reward-curve/try-runtime",
	"sp-consensus-beefy/try-runtime",
	"sp-session/try-runtime",
	"sp-staking/try-runtime",
	"sp-state-machine/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime"
]
runtime-benchmarks = [
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-authorship/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-session/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-staking-reward-curve/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-session/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
