[package]
name = "substrate-frame-rpc-system"
version = "38.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME's system exposed over Substrate RPC (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = { workspace = true }
codec = { workspace = true, default-features = true }
docify = { workspace = true }
jsonrpsee = { features = [
	"client-core",
	"macros",
	"server-core",
], workspace = true }
log = { workspace = true, default-features = true }
frame-system-rpc-runtime-api.workspace = true
frame-system-rpc-runtime-api.default-features = true
sc-rpc-api.workspace = true
sc-rpc-api.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[dev-dependencies]
sc-transaction-pool = { default-features = true, path = "../../../../client/transaction-pool" }
tokio = { workspace = true, default-features = true }
assert_matches = { workspace = true }
sp-tracing = { default-features = true, path = "../../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../../test-utils/runtime/client" }

[features]
std = [
	"log/std",
	"sc-rpc-api/std",
	"sc-transaction-pool/std",
	"sc-transaction-pool-api/std",
	"sp-blockchain/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-rpc-api/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"frame-system-rpc-runtime-api/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sc-rpc-api/try-runtime",
	"sc-transaction-pool/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"frame-system-rpc-runtime-api/try-runtime",
	"sp-core/try-runtime"
]
