[package]
name = "frame-metadata-hash-extension"
version = "0.5.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME signed extension for verifying the metadata hash (polkadot v1.15.0)"

[dependencies]
array-bytes = { workspace = true, default-features = true }
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
sp-runtime = { features = ["serde"], workspace = true }
frame-support.workspace = true
frame-system.workspace = true
log = { workspace = true }
docify = { workspace = true }

[dev-dependencies]
substrate-wasm-builder = { features = ["metadata-hash"], default-features = true, path = "../../utils/wasm-builder" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
sp-api = { default-features = true, path = "../../primitives/api" }
sp-transaction-pool = { default-features = true, path = "../../primitives/transaction-pool" }
merkleized-metadata = { workspace = true }
frame-metadata = { features = ["current"], workspace = true, default-features = true }
sp-tracing = { default-features = true, path = "../../primitives/tracing" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-runtime/std",
	"substrate-test-runtime-client/std",
	"substrate-wasm-builder/std"
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-transaction-pool/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"substrate-wasm-builder/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-api/try-runtime",
	"sp-runtime/try-runtime",
	"sp-transaction-pool/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"substrate-wasm-builder/try-runtime"
]
