[package]
name = "seedling-runtime"
version = "0.17.0"
description = "Seedling parachain runtime. A starter runtime for solochain to parachain migration. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame-executive.workspace = true
frame-support.workspace = true
frame-system.workspace = true
pallet-aura.workspace = true
pallet-balances.workspace = true
pallet-sudo.workspace = true
pallet-timestamp.workspace = true
sp-api.workspace = true
sp-block-builder.workspace = true
sp-consensus-aura.workspace = true
sp-core.workspace = true
sp-genesis-builder.workspace = true
sp-inherents.workspace = true
sp-offchain.workspace = true
sp-runtime.workspace = true
sp-session.workspace = true
sp-transaction-pool.workspace = true
sp-version.workspace = true
cumulus-pallet-aura-ext.workspace = true
cumulus-pallet-parachain-system.workspace = true
cumulus-pallet-solo-to-para.workspace = true
cumulus-primitives-core.workspace = true
cumulus-primitives-timestamp.workspace = true
parachain-info.workspace = true
parachains-common.workspace = true

[build-dependencies]
substrate-wasm-builder = { optional = true, workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-solo-to-para/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-timestamp/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"parachain-info/std",
	"parachains-common/std",
	"scale-info/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"substrate-wasm-builder?/std"
]
runtime-benchmarks = [
	"cumulus-pallet-aura-ext/runtime-benchmarks",
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-solo-to-para/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-primitives-timestamp/runtime-benchmarks",
	"frame-executive/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-aura/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-consensus-aura/runtime-benchmarks",
	"sp-genesis-builder/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-offchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-session/runtime-benchmarks",
	"sp-transaction-pool/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"parachain-info/runtime-benchmarks",
	"substrate-wasm-builder?/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"cumulus-pallet-aura-ext/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-solo-to-para/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"parachains-common/try-runtime",
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-consensus-aura/try-runtime",
	"sp-genesis-builder/try-runtime",
	"sp-inherents/try-runtime",
	"sp-offchain/try-runtime",
	"sp-runtime/try-runtime",
	"sp-session/try-runtime",
	"sp-transaction-pool/try-runtime",
	"sp-version/try-runtime",
	"parachain-info/try-runtime",
	"cumulus-primitives-timestamp/try-runtime",
	"substrate-wasm-builder?/try-runtime",
	"sp-core/try-runtime"
]
