[package]
name = "remote-ext-tests-bags-list"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "remote-ext-tests-bags-list (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
westend-runtime.workspace = true
westend-runtime-constants.workspace = true
westend-runtime-constants.default-features = true
pallet-bags-list-remote-tests.workspace = true
sp-tracing.workspace = true
sp-tracing.default-features = true
frame-system.workspace = true
frame-system.default-features = true
sp-core.workspace = true
sp-core.default-features = true

clap = { features = ["derive"], workspace = true }
log = { workspace = true, default-features = true }
tokio = { features = ["macros"], workspace = true, default-features = true }

[features]
std = [
	"log/std",
	"pallet-bags-list-remote-tests/std"
]
runtime-benchmarks = [
	"frame-system/runtime-benchmarks",
	"pallet-bags-list-remote-tests/runtime-benchmarks",
	"westend-runtime/runtime-benchmarks",
	"westend-runtime-constants/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"frame-system/try-runtime",
	"pallet-bags-list-remote-tests/try-runtime",
	"westend-runtime/try-runtime",
	"westend-runtime-constants/try-runtime",
	"sp-core/try-runtime"
]
