[package]
name = "sc-consensus-pow"
version = "0.43.0"
authors.workspace = true
description = "PoW consensus algorithm for substrate (polkadot v1.15.0)"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true }
codec = { features = ["derive"], workspace = true, default-features = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
thiserror = { workspace = true }
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus.workspace = true
sc-consensus.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-consensus-pow.workspace = true
sp-consensus-pow.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[features]
std = [
	"log/std",
	"sc-client-api/std",
	"sc-consensus/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"prometheus-endpoint/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-consensus-pow/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-consensus/try-runtime",
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-consensus-pow/try-runtime",
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-core/try-runtime"
]
