[package]
description = "Substrate light network protocol (polkadot v1.15.0)"
name = "sc-network-light"
version = "0.43.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
documentation = "https://docs.rs/sc-network-light"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { workspace = true }

[dependencies]
async-channel = { workspace = true }
array-bytes = { workspace = true, default-features = true }
codec = { features = [
	"derive",
], workspace = true, default-features = true }
futures = { workspace = true }
log = { workspace = true, default-features = true }
prost = { workspace = true }
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-network-types.workspace = true
sc-network-types.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
thiserror = { workspace = true }

[features]
std = [
	"log/std",
	"sc-client-api/std",
	"sc-network/std",
	"sc-network-types/std",
	"sp-blockchain/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-network/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-runtime/try-runtime",
	"sp-core/try-runtime"
]
