[package]
name = "sc-consensus-epochs"
version = "0.43.0"
authors.workspace = true
description = "Generic epochs-based utilities for consensus (polkadot v1.15.0)"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true, default-features = true }
fork-tree.workspace = true
fork-tree.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus.workspace = true
sc-consensus.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[features]
std = [
	"fork-tree/std",
	"sc-client-api/std",
	"sc-consensus/std",
	"sp-blockchain/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-consensus/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-runtime/try-runtime"
]
