[package]
name = "glutton-westend-runtime"
version = "13.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Glutton parachain runtime. (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame-benchmarking = { optional = true, workspace = true }
frame-executive.workspace = true
frame-support.workspace = true
frame-system.workspace = true
frame-system-rpc-runtime-api.workspace = true
frame-system-benchmarking = { optional = true, workspace = true }
frame-try-runtime = { optional = true, workspace = true }
pallet-aura.workspace = true
pallet-glutton.workspace = true
pallet-sudo.workspace = true
pallet-timestamp.workspace = true
sp-api.workspace = true
sp-block-builder.workspace = true
sp-consensus-aura.workspace = true
sp-core.workspace = true
sp-genesis-builder.workspace = true
sp-inherents.workspace = true
pallet-message-queue.workspace = true
sp-offchain.workspace = true
sp-runtime.workspace = true
sp-session.workspace = true
sp-storage.workspace = true
sp-transaction-pool.workspace = true
sp-version.workspace = true
xcm.workspace = true
xcm-builder.workspace = true
xcm-executor.workspace = true
cumulus-pallet-aura-ext.workspace = true
cumulus-pallet-parachain-system.workspace = true
cumulus-pallet-xcm.workspace = true
cumulus-primitives-aura.workspace = true
cumulus-primitives-core.workspace = true
cumulus-primitives-timestamp.workspace = true
parachain-info.workspace = true
parachains-common.workspace = true
testnet-parachains-constants = { features = ["westend"], workspace = true }

[build-dependencies]
substrate-wasm-builder.workspace = true
substrate-wasm-builder.default-features = true

[features]
default = ["std"]
runtime-benchmarks = [
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-glutton/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"cumulus-pallet-aura-ext/runtime-benchmarks",
	"cumulus-pallet-xcm/runtime-benchmarks",
	"cumulus-primitives-aura/runtime-benchmarks",
	"cumulus-primitives-timestamp/runtime-benchmarks",
	"frame-executive/runtime-benchmarks",
	"frame-try-runtime?/runtime-benchmarks",
	"pallet-aura/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-consensus-aura/runtime-benchmarks",
	"sp-genesis-builder/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-offchain/runtime-benchmarks",
	"sp-session/runtime-benchmarks",
	"sp-transaction-pool/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"parachain-info/runtime-benchmarks",
	"testnet-parachains-constants/runtime-benchmarks",
	"frame-system-rpc-runtime-api/runtime-benchmarks",
	"substrate-wasm-builder/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
std = [
	"codec/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-aura/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-timestamp/std",
	"frame-benchmarking?/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime?/std",
	"pallet-aura/std",
	"pallet-glutton/std",
	"pallet-message-queue/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"parachain-info/std",
	"parachains-common/std",
	"scale-info/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-storage/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"testnet-parachains-constants/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	"substrate-wasm-builder/std"
]
try-runtime = [
	"cumulus-pallet-aura-ext/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcm/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-glutton/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"parachain-info/try-runtime",
	"sp-runtime/try-runtime",
	"cumulus-primitives-aura/try-runtime",
	"cumulus-primitives-core/try-runtime",
	"frame-benchmarking?/try-runtime",
	"frame-system-benchmarking?/try-runtime",
	"parachains-common/try-runtime",
	"sp-api/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-consensus-aura/try-runtime",
	"sp-genesis-builder/try-runtime",
	"sp-inherents/try-runtime",
	"sp-offchain/try-runtime",
	"sp-session/try-runtime",
	"sp-transaction-pool/try-runtime",
	"sp-version/try-runtime",
	"xcm-builder/try-runtime",
	"xcm-executor/try-runtime",
	"testnet-parachains-constants/try-runtime",
	"cumulus-primitives-timestamp/try-runtime",
	"frame-system-rpc-runtime-api/try-runtime",
	"substrate-wasm-builder/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]

# A feature that should be enabled when the runtime should be built for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller, like logging for example.
on-chain-release-build = ["sp-api/disable-logging"]
