[package]
name = "bp-bridge-hub-rococo"
description = "Primitives of BridgeHubRococo parachain runtime. (polkadot v1.15.0)"
version = "0.17.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
bp-bridge-hub-cumulus.workspace = true
bp-runtime.workspace = true
bp-messages.workspace = true
frame-support.workspace = true
sp-api.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true

[features]
default = ["std"]
std = [
	"bp-bridge-hub-cumulus/std",
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"bp-bridge-hub-cumulus/runtime-benchmarks",
	"bp-messages/runtime-benchmarks",
	"bp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks"
]
try-runtime = [
	"bp-bridge-hub-cumulus/try-runtime",
	"bp-messages/try-runtime",
	"bp-runtime/try-runtime",
	"frame-support/try-runtime",
	"sp-api/try-runtime",
	"sp-runtime/try-runtime"
]
