[package]
name = "penpal-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Penpal emulated chain (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[dependencies]
sp-core.workspace = true
frame-support.workspace = true
xcm.workspace = true
parachains-common.workspace = true
parachains-common.default-features = true
cumulus-primitives-core.workspace = true
emulated-integration-tests-common.workspace = true
penpal-runtime.workspace = true

[features]
std = [
	"cumulus-primitives-core/std",
	"emulated-integration-tests-common/std",
	"frame-support/std",
	"sp-core/std",
	"xcm/std"
]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"emulated-integration-tests-common/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"penpal-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"cumulus-primitives-core/try-runtime",
	"emulated-integration-tests-common/try-runtime",
	"frame-support/try-runtime",
	"parachains-common/try-runtime",
	"penpal-runtime/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
