[package]
name = "substrate-test-runtime-transaction-pool"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false
description = "substrate-test-runtime-transaction-pool (polkadot v1.15.0)"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
futures = { workspace = true }
parking_lot = { workspace = true, default-features = true }
thiserror = { workspace = true }
sc-transaction-pool.workspace = true
sc-transaction-pool.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
substrate-test-runtime-client.workspace = true

[features]
std = [
	"sc-transaction-pool/std",
	"sc-transaction-pool-api/std",
	"sp-blockchain/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks"
]
try-runtime = [
	"sc-transaction-pool/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime"
]
