[package]
name = "polkadot-network-bridge"
version = "17.0.0"
description = "The Network Bridge Subsystem — protocol multiplexer for Polkadot. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
always-assert = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
gum.workspace = true
gum.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
codec = { features = ["derive"], workspace = true }
sc-network.workspace = true
sc-network.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
polkadot-node-metrics.workspace = true
polkadot-node-metrics.default-features = true
polkadot-node-network-protocol.workspace = true
polkadot-node-network-protocol.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-overseer.workspace = true
polkadot-overseer.default-features = true
parking_lot = { workspace = true, default-features = true }
bytes = { workspace = true, default-features = true }
fatality = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-node-subsystem-util = { default-features = true, path = "../../subsystem-util" }
sp-core = { default-features = true, path = "../../../../substrate/primitives/core" }
sp-keyring = { default-features = true, path = "../../../../substrate/primitives/keyring" }
futures-timer = { workspace = true }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }

[features]
std = [
	"codec/std",
	"polkadot-node-metrics/std",
	"polkadot-node-network-protocol/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-overseer/std",
	"polkadot-primitives-test-helpers/std",
	"sc-network/std",
	"sp-consensus/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-metrics/runtime-benchmarks",
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-overseer/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-metrics/try-runtime",
	"polkadot-node-network-protocol/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-overseer/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"sc-network/try-runtime",
	"sp-consensus/try-runtime",
	"sp-keyring/try-runtime",
	"gum/try-runtime",
	"sp-core/try-runtime"
]
