[package]
name = "polkadot-node-core-prospective-parachains"
version = "16.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "The Prospective Parachains subsystem. Tracks and handles prospective parachain fragments. (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gum.workspace = true
gum.default-features = true
thiserror = { workspace = true }
fatality = { workspace = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true

[dev-dependencies]
assert_matches = { workspace = true }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
sp-tracing = { path = "../../../../substrate/primitives/tracing", default-features = false }
sp-core = { default-features = true, path = "../../../../substrate/primitives/core" }
rand = { workspace = true }
rstest = { workspace = true }

[features]
std = [
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-util/std",
	"polkadot-primitives-test-helpers/std",
	"rand/std",
	"sp-tracing/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-primitives-test-helpers/try-runtime",
	"gum/try-runtime",
	"sp-core/try-runtime"
]
