[package]
description = "Substrate offchain workers primitives (polkadot v1.15.0)"
name = "sp-offchain"
version = "34.0.0"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true

[features]
default = ["std"]
std = ["sp-api/std", "sp-core/std", "sp-runtime/std"]
runtime-benchmarks = [
	"sp-api/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sp-api/try-runtime",
	"sp-runtime/try-runtime",
	"sp-core/try-runtime"
]
