[package]
name = "staging-node-inspect"
version = "0.22.0"
authors.workspace = true
description = "Substrate node block inspection tool. (polkadot v1.15.0)"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { features = ["derive"], workspace = true }
codec = { workspace = true, default-features = true }
thiserror = { workspace = true }
sc-cli.workspace = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-service.workspace = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-io.workspace = true
sp-io.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-statement-store.workspace = true
sp-statement-store.default-features = true

[features]
runtime-benchmarks = [
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sc-cli/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-statement-store/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
std = [
	"sc-cli/std",
	"sc-client-api/std",
	"sc-service/std",
	"sp-blockchain/std"
]
try-runtime = [
	"sc-cli/try-runtime",
	"sc-client-api/try-runtime",
	"sc-service/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-runtime/try-runtime",
	"sp-statement-store/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime"
]
