[package]
name = "sc-consensus-grandpa-rpc"
version = "0.29.0"
authors.workspace = true
description = "RPC extensions for the GRANDPA finality gadget (polkadot v1.15.0)"
repository.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
readme = "README.md"
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
finality-grandpa = { features = ["derive-codec"], workspace = true, default-features = true }
futures = { workspace = true }
jsonrpsee = { features = ["client-core", "macros", "server-core"], workspace = true }
log = { workspace = true, default-features = true }
codec = { features = ["derive"], workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
thiserror = { workspace = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus-grandpa.workspace = true
sc-consensus-grandpa.default-features = true
sc-rpc.workspace = true
sc-rpc.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[dev-dependencies]
sc-block-builder = { default-features = true, path = "../../../block-builder" }
sc-rpc = { features = ["test-helpers"], default-features = true, path = "../../../rpc" }
sp-core = { default-features = true, path = "../../../../primitives/core" }
sp-consensus-grandpa = { default-features = true, path = "../../../../primitives/consensus/grandpa" }
sp-keyring = { default-features = true, path = "../../../../primitives/keyring" }
substrate-test-runtime-client = { path = "../../../../test-utils/runtime/client" }
tokio = { features = ["macros"], workspace = true, default-features = true }

[features]
std = [
	"log/std",
	"sc-block-builder/std",
	"sc-client-api/std",
	"sc-consensus-grandpa/std",
	"sc-rpc/std",
	"sp-blockchain/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-block-builder/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus-grandpa/runtime-benchmarks",
	"sc-rpc/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-grandpa/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sc-block-builder/try-runtime",
	"sc-client-api/try-runtime",
	"sc-consensus-grandpa/try-runtime",
	"sc-rpc/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus-grandpa/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sp-core/try-runtime"
]
