[package]
name = "polkadot-test-malus"
description = "Misbehaving nodes for local testnets, system and Simnet tests. (polkadot v1.15.0)"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
publish = false

[lints]
workspace = true

[[bin]]
name = "malus"
path = "src/malus.rs"

# Use artifact dependencies once stable.
# See https://github.com/rust-lang/cargo/issues/9096.
[[bin]]
name = "polkadot-execute-worker"
path = "../../src/bin/execute-worker.rs"
# Prevent rustdoc error. Already documented from top-level Cargo.toml.
doc = false
[[bin]]
name = "polkadot-prepare-worker"
path = "../../src/bin/prepare-worker.rs"
# Prevent rustdoc error. Already documented from top-level Cargo.toml.
doc = false

[dependencies]
polkadot-cli = { features = ["malus", "rococo-native", "westend-native"], workspace = true, default-features = true }
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-node-subsystem-types.workspace = true
polkadot-node-subsystem-types.default-features = true
polkadot-node-core-dispute-coordinator.workspace = true
polkadot-node-core-dispute-coordinator.default-features = true
polkadot-node-core-candidate-validation.workspace = true
polkadot-node-core-candidate-validation.default-features = true
polkadot-node-core-backing.workspace = true
polkadot-node-core-backing.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-network-protocol.workspace = true
polkadot-node-network-protocol.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
color-eyre = { workspace = true }
assert_matches = { workspace = true }
async-trait = { workspace = true }
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-core.workspace = true
sp-core.default-features = true
clap = { features = ["derive"], workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
gum.workspace = true
gum.default-features = true
polkadot-erasure-coding.workspace = true
polkadot-erasure-coding.default-features = true
rand = { workspace = true, default-features = true }
polkadot-node-core-pvf-common.workspace = true
polkadot-node-core-pvf-common.default-features = true
polkadot-node-core-pvf-execute-worker.workspace = true
polkadot-node-core-pvf-execute-worker.default-features = true
polkadot-node-core-pvf-prepare-worker.workspace = true
polkadot-node-core-pvf-prepare-worker.default-features = true

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
sp-core = { default-features = true, path = "../../../substrate/primitives/core" }
futures = { features = ["thread-pool"], workspace = true }

[build-dependencies]
substrate-build-script-utils.workspace = true
substrate-build-script-utils.default-features = true

[features]
default = []
fast-runtime = ["polkadot-cli/fast-runtime"]
std = [
	"polkadot-cli/std",
	"polkadot-erasure-coding/std",
	"polkadot-node-core-backing/std",
	"polkadot-node-core-candidate-validation/std",
	"polkadot-node-core-dispute-coordinator/std",
	"polkadot-node-core-pvf-common/std",
	"polkadot-node-core-pvf-execute-worker/std",
	"polkadot-node-core-pvf-prepare-worker/std",
	"polkadot-node-network-protocol/std",
	"polkadot-node-primitives/std",
	"polkadot-node-subsystem-test-helpers/std",
	"polkadot-node-subsystem-types/std",
	"polkadot-node-subsystem-util/std",
	"gum/std",
	"polkadot-node-subsystem/std"
]
runtime-benchmarks = [
	"polkadot-cli/runtime-benchmarks",
	"polkadot-erasure-coding/runtime-benchmarks",
	"polkadot-node-core-backing/runtime-benchmarks",
	"polkadot-node-core-candidate-validation/runtime-benchmarks",
	"polkadot-node-core-dispute-coordinator/runtime-benchmarks",
	"polkadot-node-core-pvf-common/runtime-benchmarks",
	"polkadot-node-core-pvf-execute-worker/runtime-benchmarks",
	"polkadot-node-core-pvf-prepare-worker/runtime-benchmarks",
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-types/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"polkadot-cli/try-runtime",
	"polkadot-node-core-pvf-prepare-worker/try-runtime",
	"polkadot-node-network-protocol/try-runtime",
	"polkadot-node-primitives/try-runtime",
	"polkadot-node-subsystem-types/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-erasure-coding/try-runtime",
	"polkadot-node-core-backing/try-runtime",
	"polkadot-node-core-candidate-validation/try-runtime",
	"polkadot-node-core-dispute-coordinator/try-runtime",
	"polkadot-node-core-pvf-common/try-runtime",
	"polkadot-node-core-pvf-execute-worker/try-runtime",
	"polkadot-node-subsystem/try-runtime",
	"polkadot-node-subsystem-test-helpers/try-runtime",
	"polkadot-node-subsystem-util/try-runtime",
	"gum/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
