[package]
name = "pallet-nomination-pools-test-delegate-stake"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME nomination pools pallet tests with the staking pallet (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
codec = { features = ["derive"], workspace = true, default-features = true }
scale-info = { features = ["derive"], workspace = true, default-features = true }

sp-runtime = { default-features = true, path = "../../../primitives/runtime" }
sp-io = { default-features = true, path = "../../../primitives/io" }
sp-std = { default-features = true, path = "../../../primitives/std" }
sp-staking = { default-features = true, path = "../../../primitives/staking" }
sp-core = { default-features = true, path = "../../../primitives/core" }

frame-system = { default-features = true, path = "../../system" }
frame-support = { default-features = true, path = "../../support" }
frame-election-provider-support = { default-features = true, path = "../../election-provider-support" }

pallet-timestamp = { default-features = true, path = "../../timestamp" }
pallet-balances = { default-features = true, path = "../../balances" }
pallet-staking = { default-features = true, path = "../../staking" }
pallet-delegated-staking = { default-features = true, path = "../../delegated-staking" }
pallet-bags-list = { default-features = true, path = "../../bags-list" }
pallet-staking-reward-curve = { default-features = true, path = "../../staking/reward-curve" }
pallet-nomination-pools = { default-features = true, path = ".." }

sp-tracing = { default-features = true, path = "../../../primitives/tracing" }
log = { workspace = true, default-features = true }

[features]
std = [
	"log/std",
	"pallet-staking-reward-curve/std"
]
runtime-benchmarks = [
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-delegated-staking/runtime-benchmarks",
	"pallet-nomination-pools/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-staking-reward-curve/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-bags-list/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-delegated-staking/try-runtime",
	"pallet-nomination-pools/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-staking-reward-curve/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
	"sp-staking/try-runtime",
	"sp-io/try-runtime",
	"sp-core/try-runtime"
]
