[package]
name = "bp-test-utils"
version = "0.17.0"
description = "Utilities for testing substrate-based runtime bridge code (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
bp-header-chain.workspace = true
bp-parachains.workspace = true
bp-polkadot-core.workspace = true
bp-runtime = { features = ["test-helpers"], workspace = true }
codec = { workspace = true }
ed25519-dalek = { workspace = true }
finality-grandpa = { workspace = true }
sp-application-crypto.workspace = true
sp-consensus-grandpa.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true
sp-trie.workspace = true

[features]
default = ["std"]
std = [
	"bp-header-chain/std",
	"bp-parachains/std",
	"bp-polkadot-core/std",
	"bp-runtime/std",
	"codec/std",
	"ed25519-dalek/std",
	"finality-grandpa/std",
	"sp-application-crypto/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
]
runtime-benchmarks = [
	"bp-header-chain/runtime-benchmarks",
	"bp-parachains/runtime-benchmarks",
	"bp-polkadot-core/runtime-benchmarks",
	"bp-runtime/runtime-benchmarks",
	"sp-consensus-grandpa/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"bp-header-chain/try-runtime",
	"bp-parachains/try-runtime",
	"bp-polkadot-core/try-runtime",
	"bp-runtime/try-runtime",
	"sp-consensus-grandpa/try-runtime",
	"sp-runtime/try-runtime",
	"sp-trie/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime"
]
