[package]
name = "sc-chain-spec"
version = "37.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate chain configurations. (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { features = ["derive"], optional = true, workspace = true }
codec = { features = ["derive"], workspace = true }
memmap2 = { workspace = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-chain-spec-derive.workspace = true
sc-chain-spec-derive.default-features = true
sc-executor.workspace = true
sc-executor.default-features = true
sp-io.workspace = true
sc-network.workspace = true
sc-network.default-features = true
sc-telemetry.workspace = true
sc-telemetry.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-crypto-hashing.workspace = true
sp-crypto-hashing.default-features = true
sp-genesis-builder.workspace = true
sp-genesis-builder.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
log = { workspace = true }
sp-tracing.workspace = true
sp-tracing.default-features = true
array-bytes = { workspace = true, default-features = true }
docify = { workspace = true }

[dev-dependencies]
substrate-test-runtime = { path = "../../test-utils/runtime" }
sp-keyring = { default-features = true, path = "../../primitives/keyring" }
sp-application-crypto = { features = ["serde"], path = "../../primitives/application-crypto", default-features = false }
sp-consensus-babe = { features = ["serde"], path = "../../primitives/consensus/babe", default-features = false }
regex = { workspace = true }

[features]
std = [
	"log/std",
	"codec/std",
	"sc-client-api/std",
	"sc-network/std",
	"sc-telemetry/std",
	"sp-application-crypto/std",
	"sp-blockchain/std",
	"sp-consensus-babe/std",
	"sp-io/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-executor/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-genesis-builder/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"substrate-test-runtime/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-executor/try-runtime",
	"sc-network/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-genesis-builder/try-runtime",
	"sp-keyring/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"substrate-test-runtime/try-runtime",
	"sc-telemetry/try-runtime",
	"sp-io/try-runtime",
	"sp-application-crypto/try-runtime",
	"sp-core/try-runtime"
]
