[package]
name = "pallet-delegated-staking"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME delegated staking pallet (polkadot v1.15.0)"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
frame-support.workspace = true
frame-system.workspace = true
scale-info = { features = ["derive"], workspace = true }
sp-runtime.workspace = true
sp-staking.workspace = true

[dev-dependencies]
sp-core = { default-features = true, path = "../../primitives/core" }
sp-io = { default-features = true, path = "../../primitives/io" }
substrate-test-utils = { path = "../../test-utils" }
sp-tracing = { default-features = true, path = "../../primitives/tracing" }
pallet-staking = { default-features = true, path = "../staking" }
pallet-nomination-pools = { default-features = true, path = "../nomination-pools" }
pallet-balances = { default-features = true, path = "../balances" }
pallet-timestamp = { default-features = true, path = "../timestamp" }
pallet-staking-reward-curve = { default-features = true, path = "../staking/reward-curve" }
frame-election-provider-support = { path = "../election-provider-support", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-staking/std",
	"frame-election-provider-support/std",
	"pallet-staking-reward-curve/std",
	"substrate-test-utils/std"
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-nomination-pools/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-staking-reward-curve/runtime-benchmarks",
	"substrate-test-utils/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
	"frame-election-provider-support/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-nomination-pools/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-staking-reward-curve/try-runtime",
	"sp-staking/try-runtime",
	"sp-io/try-runtime",
	"substrate-test-utils/try-runtime",
	"sp-core/try-runtime"
]
