[package]
description = "Substrate mixnet service (polkadot v1.15.0)"
name = "sc-mixnet"
version = "0.14.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition.workspace = true
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { workspace = true, default-features = true }
arrayvec = { workspace = true }
blake2 = { workspace = true, default-features = true }
bytes = { workspace = true, default-features = true }
codec = { features = ["derive"], workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
mixnet = { workspace = true }
multiaddr = { workspace = true }
parking_lot = { workspace = true, default-features = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sc-network-types.workspace = true
sc-network-types.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-mixnet.workspace = true
sp-mixnet.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
thiserror = { workspace = true }

[features]
std = [
	"log/std",
	"codec/std",
	"sc-client-api/std",
	"sc-network/std",
	"sc-network-types/std",
	"sc-transaction-pool-api/std",
	"sp-consensus/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-mixnet/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-network/try-runtime",
	"sc-transaction-pool-api/try-runtime",
	"sp-api/try-runtime",
	"sp-consensus/try-runtime",
	"sp-runtime/try-runtime",
	"sp-mixnet/try-runtime",
	"sp-core/try-runtime",
	"sp-keystore/try-runtime"
]
