[package]
description = "Gossiping for the Substrate network protocol (polkadot v1.15.0)"
name = "sc-network-gossip"
version = "0.44.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
documentation = "https://docs.rs/sc-network-gossip"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ahash = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
schnellru = { workspace = true }
tracing = { workspace = true, default-features = true }
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sc-network-common.workspace = true
sc-network-common.default-features = true
sc-network-sync.workspace = true
sc-network-sync.default-features = true
sc-network-types.workspace = true
sc-network-types.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true

[dev-dependencies]
tokio = { workspace = true, default-features = true }
async-trait = { workspace = true }
codec = { features = ["derive"], workspace = true, default-features = true }
quickcheck = { workspace = true }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }

[features]
std = [
	"log/std",
	"sc-network/std",
	"sc-network-common/std",
	"sc-network-sync/std",
	"sc-network-types/std",
	"prometheus-endpoint/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-network/runtime-benchmarks",
	"sc-network-common/runtime-benchmarks",
	"sc-network-sync/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks"
]
try-runtime = [
	"sc-network/try-runtime",
	"sc-network-common/try-runtime",
	"sc-network-sync/try-runtime",
	"sp-runtime/try-runtime",
	"substrate-test-runtime-client/try-runtime"
]
