[package]
name = "test-runtime-constants"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "test-runtime-constants (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
smallvec = { workspace = true, default-features = true }
frame-support.workspace = true
polkadot-primitives.workspace = true
sp-runtime.workspace = true

[features]
default = ["std"]
std = [
	"frame-support/std",
	"polkadot-primitives/std",
	"sp-runtime/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"polkadot-primitives/try-runtime",
	"sp-runtime/try-runtime"
]
