[package]
name = "polkadot-test-runtime"
build = "build.rs"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-test-runtime (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
serde = { workspace = true }
sp-authority-discovery.workspace = true
sp-consensus-babe.workspace = true
sp-consensus-beefy.workspace = true
sp-api.workspace = true
sp-inherents.workspace = true
sp-offchain.workspace = true
sp-io.workspace = true
sp-runtime.workspace = true
sp-staking.workspace = true
sp-core.workspace = true
sp-genesis-builder.workspace = true
sp-mmr-primitives.workspace = true
sp-session.workspace = true
sp-version.workspace = true
frame-election-provider-support.workspace = true
sp-transaction-pool.workspace = true
sp-block-builder.workspace = true
pallet-authority-discovery.workspace = true
pallet-authorship.workspace = true
pallet-babe.workspace = true
pallet-balances.workspace = true
pallet-transaction-payment.workspace = true
pallet-transaction-payment-rpc-runtime-api.workspace = true
frame-executive.workspace = true
pallet-grandpa.workspace = true
pallet-indices.workspace = true
pallet-offences.workspace = true
pallet-session.workspace = true
frame-support.workspace = true
pallet-staking.workspace = true
pallet-staking-reward-curve.workspace = true
pallet-staking-reward-curve.default-features = true
frame-system.workspace = true
frame-system-rpc-runtime-api.workspace = true
test-runtime-constants.workspace = true
pallet-timestamp.workspace = true
pallet-sudo.workspace = true
pallet-vesting.workspace = true
polkadot-runtime-common.workspace = true
polkadot-primitives.workspace = true
pallet-xcm.workspace = true
polkadot-runtime-parachains.workspace = true
xcm-builder.workspace = true
xcm-executor.workspace = true
xcm.workspace = true

[dev-dependencies]
hex-literal = { workspace = true, default-features = true }
tiny-keccak = { features = ["keccak"], workspace = true }
sp-keyring = { default-features = true, path = "../../../substrate/primitives/keyring" }
sp-trie = { default-features = true, path = "../../../substrate/primitives/trie" }
serde_json = { workspace = true, default-features = true }

[build-dependencies]
substrate-wasm-builder.workspace = true
substrate-wasm-builder.default-features = true

[features]
default = ["std"]
no_std = []
only-staking = []
runtime-metrics = [
	"polkadot-runtime-parachains/runtime-metrics",
	"sp-io/with-tracing",
]

std = [
	"codec/std",
	"frame-election-provider-support/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"log/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-vesting/std",
	"pallet-xcm/std",
	"polkadot-primitives/std",
	"polkadot-runtime-common/std",
	"polkadot-runtime-parachains/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	"sp-authority-discovery/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-consensus-beefy/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-mmr-primitives/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"test-runtime-constants/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	"pallet-staking-reward-curve/std",
	"substrate-wasm-builder/std"
]

runtime-benchmarks = [
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"frame-executive/runtime-benchmarks",
	"pallet-authority-discovery/runtime-benchmarks",
	"pallet-authorship/runtime-benchmarks",
	"pallet-session/runtime-benchmarks",
	"pallet-staking-reward-curve/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"pallet-transaction-payment-rpc-runtime-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-genesis-builder/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-mmr-primitives/runtime-benchmarks",
	"sp-offchain/runtime-benchmarks",
	"sp-session/runtime-benchmarks",
	"sp-transaction-pool/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"test-runtime-constants/runtime-benchmarks",
	"frame-system-rpc-runtime-api/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"substrate-wasm-builder/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-staking-reward-curve/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-transaction-payment-rpc-runtime-api/try-runtime",
	"pallet-vesting/try-runtime",
	"pallet-xcm/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"polkadot-runtime-parachains/try-runtime",
	"sp-api/try-runtime",
	"sp-authority-discovery/try-runtime",
	"sp-block-builder/try-runtime",
	"sp-consensus-babe/try-runtime",
	"sp-consensus-beefy/try-runtime",
	"sp-genesis-builder/try-runtime",
	"sp-inherents/try-runtime",
	"sp-keyring/try-runtime",
	"sp-mmr-primitives/try-runtime",
	"sp-offchain/try-runtime",
	"sp-runtime/try-runtime",
	"sp-session/try-runtime",
	"sp-staking/try-runtime",
	"sp-transaction-pool/try-runtime",
	"sp-trie/try-runtime",
	"sp-version/try-runtime",
	"xcm-builder/try-runtime",
	"xcm-executor/try-runtime",
	"test-runtime-constants/try-runtime",
	"frame-system-rpc-runtime-api/try-runtime",
	"sp-io/try-runtime",
	"substrate-wasm-builder/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
