[package]
name = "sc-consensus-slots"
version = "0.43.0"
authors.workspace = true
description = "Generic slots-based utilities for consensus (polkadot v1.15.0)"
edition.workspace = true
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus.workspace = true
sc-consensus.default-features = true
sc-telemetry.workspace = true
sc-telemetry.default-features = true
sp-arithmetic.workspace = true
sp-arithmetic.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-consensus-slots.workspace = true
sp-consensus-slots.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true

[dev-dependencies]
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }

[features]
std = [
	"log/std",
	"sc-client-api/std",
	"sc-consensus/std",
	"sc-telemetry/std",
	"sp-blockchain/std",
	"sp-consensus/std",
	"substrate-test-runtime-client/std"
]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"sc-client-api/try-runtime",
	"sc-consensus/try-runtime",
	"sp-blockchain/try-runtime",
	"sp-consensus/try-runtime",
	"sp-inherents/try-runtime",
	"sp-runtime/try-runtime",
	"sp-state-machine/try-runtime",
	"substrate-test-runtime-client/try-runtime",
	"sc-telemetry/try-runtime",
	"sp-consensus-slots/try-runtime",
	"sp-core/try-runtime"
]
